obj-m :=usb_passage.o                       
#module-objs := file1.o file.o       
#GCC = /home/workspace/chenyujun/9344_Bluetooth/9344/build/gcc-4.3.3/build_mips/staging_dir/usr/bin/mips-linux-uclibc-gcc
#KDIR :=/home/workspace/chenyujun/9344_Bluetooth/9344/linux/kernels/mips-linux-2.6.31
#KDIR :=/home/zhangbo/9344/linux/kernels/mips-linux-2.6.31
#PWD := $(shell pwd)                  
#all:      
#	make	-C	$(KDIR)	SUBDIRS=$(PWD)	modules  
#	@rm -rf *.mod.*  
#	@rm -rf .*.cmd  
#	@rm -rf *.o  
#	@rm -rf Module.* 
#	@rm -rf *.order
#clean:  
#	rm -rf *.ko  

