#!/bin/sh

ROUTE_FILE=/configure_backup/route.conf

ID_IP_ADDR=`cfg -e | grep "DELXXX" |awk -F'=' '{print $2}'`
# $ID_IP_ADDR
if [ -z $ID_IP_ADDR ];then
	exit 2
fi

DES_IP_ADDR=`sed -n ${ID_IP_ADDR}'p' $ROUTE_FILE | awk  -F' ' '{print $1}'`
DES_NETMASK=`sed -n ${ID_IP_ADDR}'p' $ROUTE_FILE | awk  -F' ' '{print $2}'`
DES_GW=`sed -n ${ID_IP_ADDR}'p' $ROUTE_FILE | awk  -F' ' '{print $3}'`
sed -i ${ID_IP_ADDR}'d' $ROUTE_FILE
#echo $DES_IP_ADDR
route del -net $DES_IP_ADDR netmask $DES_NETMASK gw $DES_GW
echo "done"
#fi
