#!/bin/sh

ROUTE_FILE=/configure_backup/route.conf

ID_IP_ADDR=`cfg -e | grep "DELXXX" |awk -F'=' '{print $2}'`
# $ID_IP_ADDR
if [ -z $ID_IP_ADDR ];then
	exit 2
fi

DES_IP_ADDR=`sed -n ${ID_IP_ADDR}'p' $ROUTE_FILE | awk  -F' ' '{print $1}'`
sed -i ${ID_IP_ADDR}'d' $ROUTE_FILE
#echo $DES_IP_ADDR
route del $DES_IP_ADDR
echo "done"
#fi
