/*
 * Copyright (c) 2010, Atheros Communications Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
 * ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
 * ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 * OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef _IEEE80211_BTAMP_CONN_PRIVATE_H_
#define _IEEE80211_BTAMP_CONN_PRIVATE_H_

typedef enum _btamp_conn_event {
    IEEE80211_BTAMP_CONN_EVENT_CONNECT_REQUEST,
    IEEE80211_BTAMP_CONN_EVENT_DISCONNECT_REQUEST,
    IEEE80211_BTAMP_CONN_EVENT_JOIN_COMPLETE,
    IEEE80211_BTAMP_CONN_EVENT_AUTH_SUCCESS,
    IEEE80211_BTAMP_CONN_EVENT_AUTH_FAIL,
    IEEE80211_BTAMP_CONN_EVENT_ASSOC_SUCCESS,
    IEEE80211_BTAMP_CONN_EVENT_ASSOC_FAIL,
    IEEE80211_BTAMP_CONN_EVENT_TIMEOUT,
    IEEE80211_BTAMP_CONN_EVENT_DEAUTH,
    IEEE80211_BTAMP_CONN_EVENT_DISASSOC,
    IEEE80211_BTAMP_CONN_EVENT_KEYPLUMB,
} BTAMP_CONN_EVENT, *PBTAMP_CONN_EVENT;

typedef enum _btamp_conn_state {
    IEEE80211_BTAMP_CONN_STATE_BEACONING,
    IEEE80211_BTAMP_CONN_STATE_JOIN,
    IEEE80211_BTAMP_CONN_STATE_AUTH,
    IEEE80211_BTAMP_CONN_STATE_ASSOC,
    IEEE80211_BTAMP_CONN_STATE_CONNECTED,
    IEEE80211_BTAMP_CONN_STATE_SECURED
} BTAMP_CONN_STATE, *PBTAMP_CONN_STATE;

#endif
