#!/bin/sh
DOMAIN1=www.baidu.com 
DOMAIN2=www.google.cn 
DOMAIN3=8.8.8.8
 
while true  
do
ping -c 2 $DOMAIN3 >/dev/null 2>&1
echo -n $? > /tmp/network-status 
ping -c 2 $DOMAIN1 >/dev/null 2>&1
echo -n $? > /tmp/network-status 
ping -c 2 $DOMAIN2 >/dev/null 2>&1
echo -n $? >> /tmp/network-status 
STATUS=`cat /tmp/network-status` 
  
if [ "$STATUS" -eq 111 ];then  
	cfg -a INTERNET_ON=off
elif [ "$STATUS" -eq 011 ];then
	echo "nameserver 8.8.8.8" > /etc/resolv.conf
else
	cfg -a INTERNET_ON=on
fi 
cfg -c

sleep 1

done