#!/bin/sh
###############net_test
BAIDU=www.baidu.com
BAIDU_IP=202.108.22.5
DNS=8.8.8.8

while true
do
#echo link up 2
ping $BAIDU_IP test
if [ $? -eq 0 ]; then
	#echo link up 3
	ping $BAIDU test
	#echo link up 4
	if [ $? -eq 0 ]; then
		echo "1">/usr/www/ping.xml
	else
		echo "0">/usr/www/ping.xml
	fi
	else
		echo "0">/usr/www/ping.xml
	fi
#cfg -c
sleep 3
done
