#!/bin/sh

BAIDU=www.baidu.com
QQ=www.qq.com
sleep 3
ping_flag=`cat /usr/www/ping.xml`
if [ "$ping_flag" -eq 0 ]; then
        PING_BD=NO
	PING_QQ=NO
else
        PING_BD=OK
	PING_QQ=OK
fi

if [ "$PING_QQ" = "NO" -a "$PING_BD" = "NO" ]; then
	 cfg -a INTERNET_ON=off
	 cfg -a PING_BD=NO
	 cfg -a PING_QQ=NO
	 NCHECK=no
else
	 cfg -a AUTOTYPE=`cfg -e | grep "WAN_MODE" |awk -F'=' '{print $2}'`
	 cfg -a INTERNET_ON=on
	 cfg -a PING_BD=OK
	 cfg -a PING_QQ=OK
	 NCHECK=yes
fi

cfg -c

if [ "$NCHECK" = "yes" ]; then
	exit 1
else
	net_check
fi
