#!/bin/sh

BAIDU=www.baidu.com
BAIDU_IP=202.108.22.5
DNS=8.8.8.8

#echo link up 2
#ping $BAIDU_IP test
if ping -c 1 $BAIDU_IP 2>/dev/null |grep "ttl=[0-9]\+"
then
	PING_BD=OK
	PING_QQ=OK
else
	PING_BD=NO
	PING_QQ=NO
fi


if [ "$PING_QQ" = "NO" -a "$PING_BD" = "NO" ]; then
	 cfg -a INTERNET_ON=off
	 cfg -a PING_BD=NO
	 cfg -a PING_QQ=NO
	 NCHECK=no
else
	 cfg -a AUTOTYPE=`cfg -e | grep "WAN_MODE" |awk -F'=' '{print $2}'`
	 type=`cfg -e | grep "WAN_MODE" |awk -F'=' '{print $2}'`
	 cfg -a INTERNET_ON=on
	 cfg -a PING_BD=OK
	 cfg -a PING_QQ=OK
	 NCHECK=yes
fi

cfg -c

if [ "$NCHECK" = "yes" ]; then
	echo $type
	exit 1
else
	net_check
fi
