#!/bin/sh
if [ $# -ne 1 ] ;then
#        echo "Usage: sysupgrade [SYSTEM-FILENAME]"
        exit 1
fi

if [ ! -e $1 ];then
#	echo "the file is not exist"
	exit 1
fi

sync

killall telnetd udhcpc udhcpd pppoe-connect > /dev/null 2>&1

mkdir  -p bin
mkdir  -p lib
mkdir  -p dev
mkdir  -p tmp
mkdir  -p etc
mkdir  -p sbin
mkdir  -p proc
mkdir  -p oldroot
mkdir  -p newroot
mkdir  -p usr
mkdir  -p usr/bin
mkdir  -p usr/sbin

cp -f /bin/busybox bin

cp -a /bin/echo bin
cp -a /bin/cp bin
cp -a /bin/sleep bin
cp -a /bin/sync bin
cp -a /bin/kill bin
cp -a /bin/tar bin
cp -a /bin/dd bin
cp -a /bin/rm bin
cp -a /bin/mount bin
cp -a /bin/umount bin
cp -a /bin/sh bin
cp -a /bin/ash bin
cp -a /bin/sed bin
#cp -a /usr/bin/logger bin
cp -a /usr/bin/wc bin
cp -a /usr/bin/expr bin
cp -a /usr/bin/awk bin

cp -a /sbin/pivot_root sbin
cp -a /sbin/reboot sbin
cp -a /sbin/init sbin
cp -a /sbin/getty sbin

cp -a /usr/bin/killall usr/bin
cp -a /usr/bin/cut usr/bin
cp -a /usr/bin/upgrade_stage2 usr/bin
cp -a /usr/sbin/chroot usr/sbin
cp -a /usr/bin/[ usr/bin

mv /tmp/9344version.img tmp

cp -a /lib/* lib
cp -a /dev/* dev

BOOT_TYPE="flashboot"


echo '::sysinit:/usr/bin/upgrade_stage2 '$BOOT_TYPE > etc/inittab
echo '::restart:/sbin/init'>> etc/inittab
#
# Change the root of FS to /tmp
#
./sbin/pivot_root . oldroot
cd /
mount -t proc proc /proc
mount -t tmpfs tmpfs /dev 
cp /oldroot/dev . -rf 

#echo 'Before sending HUP & SIGQUIT to init' >> /messages

exec /usr/sbin/chroot . /bin/sh -c '/bin/kill -HUP 1; /bin/sleep 3; /bin/kill -SIGQUIT 1' <dev/console >dev/console 2>&1
