#!/bin/sh
########################################
#system upgrad tool for web GUI,ap83
#parameter numbers check and usage
if [ $# -ne 1 ] ;then
#        echo "Usage: sysupgrade [SYSTEM-FILENAME]"
        exit 1
fi

############################################
#if file exist
if [ -e $1 ]; then
#        echo "file exist!"
        cp /usr/sbin/__sysupgrade /tmp/
	mv $1 /tmp/9344version.img 

	#ROOTFS_SIZE=14876672
	ROOTFS_SIZE=9568256
	#KERNEL_SIZE=1441792
	KERNEL_SIZE=1048576

	SIZE=`wc -c /tmp/9344version.img | awk -F' ' '{print $1}'`
	#echo $SIZE
	if [ $SIZE -lt $KERNEL_SIZE ] || [ $SIZE -gt $ROOTFS_SIZE ];then
	        echo "wrong size"
	        exit 1
	fi
	ap_mode=`cfg -e | grep STARTMODE | awk -F'"' '{print $2}'`
	if [ "${ap_mode}" = "repeater" -o "${ap_mode}" = "repeater_wisp" ];then
		cfg -a AP_STARTMODE=dual
		cfg -r WISPON_OFF
		cfg -r WISPON_OFF_3
		cfg -r WISP_STA_SSID
		cfg -r WISP_STA_SSID_2
		cfg -r WISP_STA_PSK_KEY
		cfg -r WISP_STA_PSK_KEY_2
	
		cfg -r WDSON_OFF
		cfg -r WDSON_OFF_3
		cfg -r WDS_STA_SSID
		cfg -r WDS_STA_SSID_2
		cfg -r WDS_STA_PSK_KEY
		cfg -r WDS_STA_PSK_KEY_2
		
		cfg -c
	fi
	
	if [ "${ap_mode}" = "repeater_wisp" ];then
		wan_mode=`cfg -e | grep WAN_BACK_MODE | awk -F'=' '{print $2}'`
		cfg -a WAN_MODE=$wan_mode		
		cfg -c
	fi
	
	cd /tmp
	test1=$(/usr/sbin/firmware_check /tmp/9344version.img | grep "OK")
#	echo $test1

	if [ -z "$test1" ];then
#		echo "wrong fireware file"
		exit 1
	fi
        /tmp/__sysupgrade /tmp/9344version.img  2>&1
fi
