/*
 * Excerpts from
 * //depot/chips/wasp/1.0/rtl/apb/blueprint/apb_map.h
 */

#ifndef	_APB_MAP_H
#define	_APB_MAP_H

#define CPU_PLL_CONFIG_ADDRESS		0x18050000
#define CPU_PLL_CONFIG_PLLPWD_MASK	0x40000000
#define CPU_PLL_CONFIG_REFDIV_MASK	0x0001f000
#define CPU_PLL_CONFIG_NINT_MASK	0x00000fc0
#define CPU_PLL_CONFIG_NFRAC_MASK	0x0000003f
#define CPU_PLL_CONFIG_UPDATING_MASK	0x80000000

#define CPU_PLL_CONFIG_PLLPWD_LSB	30
#define CPU_PLL_CONFIG_REFDIV_LSB	12
#define CPU_PLL_CONFIG_NINT_LSB		6
#define CPU_PLL_CONFIG_NFRAC_LSB	0

#define CPU_PLL_CONFIG_PLLPWD_SET(x)	\
	(((x) << CPU_PLL_CONFIG_PLLPWD_LSB) & CPU_PLL_CONFIG_PLLPWD_MASK)
#define CPU_PLL_CONFIG_REFDIV_SET(x)	\
	(((x) << CPU_PLL_CONFIG_REFDIV_LSB) & CPU_PLL_CONFIG_REFDIV_MASK)
#define CPU_PLL_CONFIG_NINT_SET(x)	\
	(((x) << CPU_PLL_CONFIG_NINT_LSB) & CPU_PLL_CONFIG_NINT_MASK)
#define CPU_PLL_CONFIG_NFRAC_SET(x)	\
	(((x) << CPU_PLL_CONFIG_NFRAC_LSB) & CPU_PLL_CONFIG_NFRAC_MASK)

#define DDR_PLL_CONFIG_ADDRESS		0x18050004
#define DDR_PLL_CONFIG_PLLPWD_MASK	0x40000000
#define DDR_PLL_CONFIG_REFDIV_MASK	0x001f0000
#define DDR_PLL_CONFIG_NINT_MASK	0x0000fc00
#define DDR_PLL_CONFIG_NFRAC_MASK	0x000003ff
#define DDR_PLL_CONFIG_UPDATING_MASK	0x80000000

#define DDR_PLL_CONFIG_PLLPWD_LSB	30
#define DDR_PLL_CONFIG_REFDIV_LSB	16
#define DDR_PLL_CONFIG_NINT_LSB		10
#define DDR_PLL_CONFIG_NFRAC_LSB	0

#define DDR_PLL_CONFIG_OUTDIV_MSB	25
#define DDR_PLL_CONFIG_OUTDIV_LSB	23
#define DDR_PLL_CONFIG_OUTDIV_MASK	0x03800000
#define DDR_PLL_CONFIG_OUTDIV_GET(x)	(((x) & DDR_PLL_CONFIG_OUTDIV_MASK) >> DDR_PLL_CONFIG_OUTDIV_LSB)
#define DDR_PLL_CONFIG_OUTDIV_SET(x)	(((x) << DDR_PLL_CONFIG_OUTDIV_LSB) & DDR_PLL_CONFIG_OUTDIV_MASK)
#define DDR_PLL_CONFIG_OUTDIV_RESET	0

#define DDR_PLL_CONFIG_RANGE_MSB	22
#define DDR_PLL_CONFIG_RANGE_LSB	21
#define DDR_PLL_CONFIG_RANGE_MASK	0x00600000
#define DDR_PLL_CONFIG_RANGE_GET(x)	(((x) & DDR_PLL_CONFIG_RANGE_MASK) >> DDR_PLL_CONFIG_RANGE_LSB)
#define DDR_PLL_CONFIG_RANGE_SET(x)	(((x) << DDR_PLL_CONFIG_RANGE_LSB) & DDR_PLL_CONFIG_RANGE_MASK)
#define DDR_PLL_CONFIG_RANGE_RESET	3

#define DDR_PLL_INIT_MASK		~(DDR_PLL_CONFIG_PLLPWD_MASK |	\
					  DDR_PLL_CONFIG_REFDIV_MASK |	\
					  DDR_PLL_CONFIG_NINT_MASK |	\
					  DDR_PLL_CONFIG_OUTDIV_MASK |	\
					  DDR_PLL_CONFIG_NFRAC_MASK)

#define DDR_PLL_CONFIG_PLLPWD_SET(x)	\
	(((x) << DDR_PLL_CONFIG_PLLPWD_LSB) & DDR_PLL_CONFIG_PLLPWD_MASK)
#define DDR_PLL_CONFIG_REFDIV_SET(x)	\
	(((x) << DDR_PLL_CONFIG_REFDIV_LSB) & DDR_PLL_CONFIG_REFDIV_MASK)
#define DDR_PLL_CONFIG_NINT_SET(x)	\
	(((x) << DDR_PLL_CONFIG_NINT_LSB) & DDR_PLL_CONFIG_NINT_MASK)
#define DDR_PLL_CONFIG_NFRAC_SET(x)	\
	(((x) << DDR_PLL_CONFIG_NFRAC_LSB) & DDR_PLL_CONFIG_NFRAC_MASK)


#define CPU_DDR_CLOCK_CONTROL_ADDRESS			0x18050008
#define CPU_DDR_CLOCK_CONTROL_AHB_PLL_BYPASS_MASK	0x00000010
#define CPU_DDR_CLOCK_CONTROL_DDR_PLL_BYPASS_MASK	0x00000008
#define CPU_DDR_CLOCK_CONTROL_CPU_PLL_BYPASS_MASK	0x00000004
#define CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_MASK		0x000f8000
#define CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_MASK		0x00007c00
#define CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_MASK		0x000003e0

#define CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_LSB		15
#define CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_LSB		10
#define CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_LSB		5

#define CPU_DDR_CLOCK_CONTROL_PLL_BYPASS_MASK		\
	~(CPU_DDR_CLOCK_CONTROL_AHB_PLL_BYPASS_MASK)

#define CPU_DDR_CLOCK_CONTROL_POST_DIV_MASK		\
	~(CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_MASK |	\
	  CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_MASK |	\
	  CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_MASK)

#define CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_SET(x)		\
	(((x) << CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_LSB) &	\
		CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_MASK)

#define CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_SET(x)		\
	(((x) << CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_LSB) &	\
		CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_MASK)

#define CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_SET(x)		\
	(((x) << CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_LSB) &	\
		CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_MASK)

#define	DDR_PLL_40_INIT_VAL		(DDR_PLL_CONFIG_PLLPWD_SET(0) |	\
					 DDR_PLL_CONFIG_REFDIV_SET(1) |	\
					 DDR_PLL_CONFIG_NINT_SET(10) |	\
					 DDR_PLL_CONFIG_OUTDIV_SET(1) |	\
					 DDR_PLL_CONFIG_NFRAC_SET(0))

#define	DDR_PLL_25_INIT_VAL		(DDR_PLL_CONFIG_PLLPWD_SET(0) |	\
					 DDR_PLL_CONFIG_REFDIV_SET(1) |	\
					 DDR_PLL_CONFIG_NINT_SET(16) |	\
					 DDR_PLL_CONFIG_OUTDIV_SET(1) |	\
					 DDR_PLL_CONFIG_NFRAC_SET(0))

#define	CPU_DDR_CLOCK_CONTROL_INIT_MASK			\
	(CPU_DDR_CLOCK_CONTROL_PLL_BYPASS_MASK &	\
	 CPU_DDR_CLOCK_CONTROL_POST_DIV_MASK)

#define CPU_DDR_CLOCK_CONTROL_INIT_VAL			\
	(CPU_DDR_CLOCK_CONTROL_AHB_POST_DIV_SET(3) |	\
	 CPU_DDR_CLOCK_CONTROL_DDR_POST_DIV_SET(1) |	\
	 CPU_DDR_CLOCK_CONTROL_CPU_POST_DIV_SET(1))

#define SWITCH_CLOCK_SPARE_ADDRESS			0x18050024
#define SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_MASK		0x00000001
#define SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_MASK	0x00000f00
#define SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_LSB		0
#define SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_LSB	8


#define SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_SET(x)			\
	(((x) << SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_LSB) &	\
	 SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_MASK)

#define SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_SET(x)		\
	(((x) << SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_LSB) &	\
	 SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_MASK)


#define SWITCH_CLOCK_SPARE_INIT_MASK			\
	~(SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_MASK |	\
	  SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_MASK)

#define SWITCH_CLOCK_SPARE_40_INIT_VAL			\
	(SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_SET(0) |	\
	 SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_SET(5))

#define SWITCH_CLOCK_SPARE_25_INIT_VAL			\
	(SWITCH_CLOCK_SPARE_SWITCHCLK_SEL_SET(1) |	\
	 SWITCH_CLOCK_SPARE_USB_REFCLK_FREQ_SEL_SET(2))

#define RST_RESET_NANDF_RESET_MASK	0x00004000

// 32'h1806001c (RST_RESET)
#define RST_RESET_HOST_RESET_MSB			31
#define RST_RESET_HOST_RESET_LSB			31
#define RST_RESET_HOST_RESET_MASK			0x80000000
#define RST_RESET_HOST_RESET_GET(x)			(((x) & RST_RESET_HOST_RESET_MASK) >> RST_RESET_HOST_RESET_LSB)
#define RST_RESET_HOST_RESET_SET(x)			(((x) << RST_RESET_HOST_RESET_LSB) & RST_RESET_HOST_RESET_MASK)
// #define RST_RESET_HOST_RESET_RESET			1'd0
#define RST_RESET_SLIC_RESET_MSB			30
#define RST_RESET_SLIC_RESET_LSB			30
#define RST_RESET_SLIC_RESET_MASK			0x40000000
#define RST_RESET_SLIC_RESET_GET(x)			(((x) & RST_RESET_SLIC_RESET_MASK) >> RST_RESET_SLIC_RESET_LSB)
#define RST_RESET_SLIC_RESET_SET(x)			(((x) << RST_RESET_SLIC_RESET_LSB) & RST_RESET_SLIC_RESET_MASK)
// #define RST_RESET_SLIC_RESET_RESET			1'd0
#define RST_RESET_HDMA_RESET_MSB			29
#define RST_RESET_HDMA_RESET_LSB			29
#define RST_RESET_HDMA_RESET_MASK			0x20000000
#define RST_RESET_HDMA_RESET_GET(x)			(((x) & RST_RESET_HDMA_RESET_MASK) >> RST_RESET_HDMA_RESET_LSB)
#define RST_RESET_HDMA_RESET_SET(x)			(((x) << RST_RESET_HDMA_RESET_LSB) & RST_RESET_HDMA_RESET_MASK)
// #define RST_RESET_HDMA_RESET_RESET			1'd1
#define RST_RESET_EXTERNAL_RESET_MSB			28
#define RST_RESET_EXTERNAL_RESET_LSB			28
#define RST_RESET_EXTERNAL_RESET_MASK			0x10000000
#define RST_RESET_EXTERNAL_RESET_GET(x)			(((x) & RST_RESET_EXTERNAL_RESET_MASK) >> RST_RESET_EXTERNAL_RESET_LSB)
#define RST_RESET_EXTERNAL_RESET_SET(x)			(((x) << RST_RESET_EXTERNAL_RESET_LSB) & RST_RESET_EXTERNAL_RESET_MASK)
// #define RST_RESET_EXTERNAL_RESET_RESET			1'd0
#define RST_RESET_RTC_RESET_MSB				27
#define RST_RESET_RTC_RESET_LSB				27
#define RST_RESET_RTC_RESET_MASK			0x08000000
#define RST_RESET_RTC_RESET_GET(x)			(((x) & RST_RESET_RTC_RESET_MASK) >> RST_RESET_RTC_RESET_LSB)
#define RST_RESET_RTC_RESET_SET(x)			(((x) << RST_RESET_RTC_RESET_LSB) & RST_RESET_RTC_RESET_MASK)
// #define RST_RESET_RTC_RESET_RESET			1'd1
#define RST_RESET_PCIEEP_RST_INT_MSB			26
#define RST_RESET_PCIEEP_RST_INT_LSB			26
#define RST_RESET_PCIEEP_RST_INT_MASK			0x04000000
#define RST_RESET_PCIEEP_RST_INT_GET(x)			(((x) & RST_RESET_PCIEEP_RST_INT_MASK) >> RST_RESET_PCIEEP_RST_INT_LSB)
#define RST_RESET_PCIEEP_RST_INT_SET(x)			(((x) << RST_RESET_PCIEEP_RST_INT_LSB) & RST_RESET_PCIEEP_RST_INT_MASK)
// #define RST_RESET_PCIEEP_RST_INT_RESET			1'd0
#define RST_RESET_CHKSUM_ACC_RESET_MSB			25
#define RST_RESET_CHKSUM_ACC_RESET_LSB			25
#define RST_RESET_CHKSUM_ACC_RESET_MASK			0x02000000
#define RST_RESET_CHKSUM_ACC_RESET_GET(x)		(((x) & RST_RESET_CHKSUM_ACC_RESET_MASK) >> RST_RESET_CHKSUM_ACC_RESET_LSB)
#define RST_RESET_CHKSUM_ACC_RESET_SET(x)		(((x) << RST_RESET_CHKSUM_ACC_RESET_LSB) & RST_RESET_CHKSUM_ACC_RESET_MASK)
// #define RST_RESET_CHKSUM_ACC_RESET_RESET		1'd0
#define RST_RESET_FULL_CHIP_RESET_MSB			24
#define RST_RESET_FULL_CHIP_RESET_LSB			24
#define RST_RESET_FULL_CHIP_RESET_MASK			0x01000000
#define RST_RESET_FULL_CHIP_RESET_GET(x)		(((x) & RST_RESET_FULL_CHIP_RESET_MASK) >> RST_RESET_FULL_CHIP_RESET_LSB)
#define RST_RESET_FULL_CHIP_RESET_SET(x)		(((x) << RST_RESET_FULL_CHIP_RESET_LSB) & RST_RESET_FULL_CHIP_RESET_MASK)
// #define RST_RESET_FULL_CHIP_RESET_RESET			1'd0
#define RST_RESET_GE1_MDIO_RESET_MSB			23
#define RST_RESET_GE1_MDIO_RESET_LSB			23
#define RST_RESET_GE1_MDIO_RESET_MASK			0x00800000
#define RST_RESET_GE1_MDIO_RESET_GET(x)			(((x) & RST_RESET_GE1_MDIO_RESET_MASK) >> RST_RESET_GE1_MDIO_RESET_LSB)
#define RST_RESET_GE1_MDIO_RESET_SET(x)			(((x) << RST_RESET_GE1_MDIO_RESET_LSB) & RST_RESET_GE1_MDIO_RESET_MASK)
// #define RST_RESET_GE1_MDIO_RESET_RESET			1'd1
#define RST_RESET_GE0_MDIO_RESET_MSB			22
#define RST_RESET_GE0_MDIO_RESET_LSB			22
#define RST_RESET_GE0_MDIO_RESET_MASK			0x00400000
#define RST_RESET_GE0_MDIO_RESET_GET(x)			(((x) & RST_RESET_GE0_MDIO_RESET_MASK) >> RST_RESET_GE0_MDIO_RESET_LSB)
#define RST_RESET_GE0_MDIO_RESET_SET(x)			(((x) << RST_RESET_GE0_MDIO_RESET_LSB) & RST_RESET_GE0_MDIO_RESET_MASK)
// #define RST_RESET_GE0_MDIO_RESET_RESET			1'd1
#define RST_RESET_CPU_NMI_MSB				21
#define RST_RESET_CPU_NMI_LSB				21
#define RST_RESET_CPU_NMI_MASK				0x00200000
#define RST_RESET_CPU_NMI_GET(x)			(((x) & RST_RESET_CPU_NMI_MASK) >> RST_RESET_CPU_NMI_LSB)
#define RST_RESET_CPU_NMI_SET(x)			(((x) << RST_RESET_CPU_NMI_LSB) & RST_RESET_CPU_NMI_MASK)
// #define RST_RESET_CPU_NMI_RESET				1'd0
#define RST_RESET_CPU_COLD_RESET_MSB			20
#define RST_RESET_CPU_COLD_RESET_LSB			20
#define RST_RESET_CPU_COLD_RESET_MASK			0x00100000
#define RST_RESET_CPU_COLD_RESET_GET(x)			(((x) & RST_RESET_CPU_COLD_RESET_MASK) >> RST_RESET_CPU_COLD_RESET_LSB)
#define RST_RESET_CPU_COLD_RESET_SET(x)			(((x) << RST_RESET_CPU_COLD_RESET_LSB) & RST_RESET_CPU_COLD_RESET_MASK)
// #define RST_RESET_CPU_COLD_RESET_RESET			1'd0
#define RST_RESET_HOST_RESET_INT_MSB			19
#define RST_RESET_HOST_RESET_INT_LSB			19
#define RST_RESET_HOST_RESET_INT_MASK			0x00080000
#define RST_RESET_HOST_RESET_INT_GET(x)			(((x) & RST_RESET_HOST_RESET_INT_MASK) >> RST_RESET_HOST_RESET_INT_LSB)
#define RST_RESET_HOST_RESET_INT_SET(x)			(((x) << RST_RESET_HOST_RESET_INT_LSB) & RST_RESET_HOST_RESET_INT_MASK)
// #define RST_RESET_HOST_RESET_INT_RESET			1'd0
#define RST_RESET_PCIEEP_RESET_MSB			18
#define RST_RESET_PCIEEP_RESET_LSB			18
#define RST_RESET_PCIEEP_RESET_MASK			0x00040000
#define RST_RESET_PCIEEP_RESET_GET(x)			(((x) & RST_RESET_PCIEEP_RESET_MASK) >> RST_RESET_PCIEEP_RESET_LSB)
#define RST_RESET_PCIEEP_RESET_SET(x)			(((x) << RST_RESET_PCIEEP_RESET_LSB) & RST_RESET_PCIEEP_RESET_MASK)
// #define RST_RESET_PCIEEP_RESET_RESET			1'd0
#define RST_RESET_UART1_RESET_MSB			17
#define RST_RESET_UART1_RESET_LSB			17
#define RST_RESET_UART1_RESET_MASK			0x00020000
#define RST_RESET_UART1_RESET_GET(x)			(((x) & RST_RESET_UART1_RESET_MASK) >> RST_RESET_UART1_RESET_LSB)
#define RST_RESET_UART1_RESET_SET(x)			(((x) << RST_RESET_UART1_RESET_LSB) & RST_RESET_UART1_RESET_MASK)
// #define RST_RESET_UART1_RESET_RESET			1'd0
#define RST_RESET_DDR_RESET_MSB				16
#define RST_RESET_DDR_RESET_LSB				16
#define RST_RESET_DDR_RESET_MASK			0x00010000
#define RST_RESET_DDR_RESET_GET(x)			(((x) & RST_RESET_DDR_RESET_MASK) >> RST_RESET_DDR_RESET_LSB)
#define RST_RESET_DDR_RESET_SET(x)			(((x) << RST_RESET_DDR_RESET_LSB) & RST_RESET_DDR_RESET_MASK)
// #define RST_RESET_DDR_RESET_RESET			1'd0
#define RST_RESET_USB_PHY_PLL_PWD_EXT_MSB		15
#define RST_RESET_USB_PHY_PLL_PWD_EXT_LSB		15
#define RST_RESET_USB_PHY_PLL_PWD_EXT_MASK		0x00008000
#define RST_RESET_USB_PHY_PLL_PWD_EXT_GET(x)		(((x) & RST_RESET_USB_PHY_PLL_PWD_EXT_MASK) >> RST_RESET_USB_PHY_PLL_PWD_EXT_LSB)
#define RST_RESET_USB_PHY_PLL_PWD_EXT_SET(x)		(((x) << RST_RESET_USB_PHY_PLL_PWD_EXT_LSB) & RST_RESET_USB_PHY_PLL_PWD_EXT_MASK)
// #define RST_RESET_USB_PHY_PLL_PWD_EXT_RESET		1'd0
#define RST_RESET_NANDF_RESET_MSB			14
#define RST_RESET_NANDF_RESET_LSB			14
#define RST_RESET_NANDF_RESET_MASK			0x00004000
#define RST_RESET_NANDF_RESET_GET(x)			(((x) & RST_RESET_NANDF_RESET_MASK) >> RST_RESET_NANDF_RESET_LSB)
#define RST_RESET_NANDF_RESET_SET(x)			(((x) << RST_RESET_NANDF_RESET_LSB) & RST_RESET_NANDF_RESET_MASK)
// #define RST_RESET_NANDF_RESET_RESET			1'd1
#define RST_RESET_GE1_MAC_RESET_MSB			13
#define RST_RESET_GE1_MAC_RESET_LSB			13
#define RST_RESET_GE1_MAC_RESET_MASK			0x00002000
#define RST_RESET_GE1_MAC_RESET_GET(x)			(((x) & RST_RESET_GE1_MAC_RESET_MASK) >> RST_RESET_GE1_MAC_RESET_LSB)
#define RST_RESET_GE1_MAC_RESET_SET(x)			(((x) << RST_RESET_GE1_MAC_RESET_LSB) & RST_RESET_GE1_MAC_RESET_MASK)
// #define RST_RESET_GE1_MAC_RESET_RESET			1'd1
#define RST_RESET_ETH_SWITCH_ARESET_MSB			12
#define RST_RESET_ETH_SWITCH_ARESET_LSB			12
#define RST_RESET_ETH_SWITCH_ARESET_MASK		0x00001000
#define RST_RESET_ETH_SWITCH_ARESET_GET(x)		(((x) & RST_RESET_ETH_SWITCH_ARESET_MASK) >> RST_RESET_ETH_SWITCH_ARESET_LSB)
#define RST_RESET_ETH_SWITCH_ARESET_SET(x)		(((x) << RST_RESET_ETH_SWITCH_ARESET_LSB) & RST_RESET_ETH_SWITCH_ARESET_MASK)
// #define RST_RESET_ETH_SWITCH_ARESET_RESET		1'd1
#define RST_RESET_USB_PHY_ARESET_MSB			11
#define RST_RESET_USB_PHY_ARESET_LSB			11
#define RST_RESET_USB_PHY_ARESET_MASK			0x00000800
#define RST_RESET_USB_PHY_ARESET_GET(x)			(((x) & RST_RESET_USB_PHY_ARESET_MASK) >> RST_RESET_USB_PHY_ARESET_LSB)
#define RST_RESET_USB_PHY_ARESET_SET(x)			(((x) << RST_RESET_USB_PHY_ARESET_LSB) & RST_RESET_USB_PHY_ARESET_MASK)
// #define RST_RESET_USB_PHY_ARESET_RESET			1'd1
#define RST_RESET_RESERVED_MSB				10
#define RST_RESET_RESERVED_LSB				10
#define RST_RESET_RESERVED_MASK				0x00000400
#define RST_RESET_RESERVED_GET(x)			(((x) & RST_RESET_RESERVED_MASK) >> RST_RESET_RESERVED_LSB)
#define RST_RESET_RESERVED_SET(x)			(((x) << RST_RESET_RESERVED_LSB) & RST_RESET_RESERVED_MASK)
// #define RST_RESET_RESERVED_RESET			1'd1
#define RST_RESET_GE0_MAC_RESET_MSB			9
#define RST_RESET_GE0_MAC_RESET_LSB			9
#define RST_RESET_GE0_MAC_RESET_MASK			0x00000200
#define RST_RESET_GE0_MAC_RESET_GET(x)			(((x) & RST_RESET_GE0_MAC_RESET_MASK) >> RST_RESET_GE0_MAC_RESET_LSB)
#define RST_RESET_GE0_MAC_RESET_SET(x)			(((x) << RST_RESET_GE0_MAC_RESET_LSB) & RST_RESET_GE0_MAC_RESET_MASK)
// #define RST_RESET_GE0_MAC_RESET_RESET			1'd1
#define RST_RESET_ETH_SWITCH_RESET_MSB			8
#define RST_RESET_ETH_SWITCH_RESET_LSB			8
#define RST_RESET_ETH_SWITCH_RESET_MASK			0x00000100
#define RST_RESET_ETH_SWITCH_RESET_GET(x)		(((x) & RST_RESET_ETH_SWITCH_RESET_MASK) >> RST_RESET_ETH_SWITCH_RESET_LSB)
#define RST_RESET_ETH_SWITCH_RESET_SET(x)		(((x) << RST_RESET_ETH_SWITCH_RESET_LSB) & RST_RESET_ETH_SWITCH_RESET_MASK)
// #define RST_RESET_ETH_SWITCH_RESET_RESET		1'd1
#define RST_RESET_PCIE_PHY_RESET_MSB			7
#define RST_RESET_PCIE_PHY_RESET_LSB			7
#define RST_RESET_PCIE_PHY_RESET_MASK			0x00000080
#define RST_RESET_PCIE_PHY_RESET_GET(x)			(((x) & RST_RESET_PCIE_PHY_RESET_MASK) >> RST_RESET_PCIE_PHY_RESET_LSB)
#define RST_RESET_PCIE_PHY_RESET_SET(x)			(((x) << RST_RESET_PCIE_PHY_RESET_LSB) & RST_RESET_PCIE_PHY_RESET_MASK)
// #define RST_RESET_PCIE_PHY_RESET_RESET			1'd1
#define RST_RESET_PCIE_RESET_MSB			6
#define RST_RESET_PCIE_RESET_LSB			6
#define RST_RESET_PCIE_RESET_MASK			0x00000040
#define RST_RESET_PCIE_RESET_GET(x)			(((x) & RST_RESET_PCIE_RESET_MASK) >> RST_RESET_PCIE_RESET_LSB)
#define RST_RESET_PCIE_RESET_SET(x)			(((x) << RST_RESET_PCIE_RESET_LSB) & RST_RESET_PCIE_RESET_MASK)
// #define RST_RESET_PCIE_RESET_RESET			1'd1
#define RST_RESET_USB_HOST_RESET_MSB			5
#define RST_RESET_USB_HOST_RESET_LSB			5
#define RST_RESET_USB_HOST_RESET_MASK			0x00000020
#define RST_RESET_USB_HOST_RESET_GET(x)			(((x) & RST_RESET_USB_HOST_RESET_MASK) >> RST_RESET_USB_HOST_RESET_LSB)
#define RST_RESET_USB_HOST_RESET_SET(x)			(((x) << RST_RESET_USB_HOST_RESET_LSB) & RST_RESET_USB_HOST_RESET_MASK)
// #define RST_RESET_USB_HOST_RESET_RESET			1'd1
#define RST_RESET_USB_PHY_RESET_MSB			4
#define RST_RESET_USB_PHY_RESET_LSB			4
#define RST_RESET_USB_PHY_RESET_MASK			0x00000010
#define RST_RESET_USB_PHY_RESET_GET(x)			(((x) & RST_RESET_USB_PHY_RESET_MASK) >> RST_RESET_USB_PHY_RESET_LSB)
#define RST_RESET_USB_PHY_RESET_SET(x)			(((x) << RST_RESET_USB_PHY_RESET_LSB) & RST_RESET_USB_PHY_RESET_MASK)
// #define RST_RESET_USB_PHY_RESET_RESET			1'd1
#define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_MSB		3
#define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_LSB		3
#define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_MASK		0x00000008
#define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_GET(x)	(((x) & RST_RESET_USB_PHY_SUSPEND_OVERRIDE_MASK) >> RST_RESET_USB_PHY_SUSPEND_OVERRIDE_LSB)
#define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_SET(x)	(((x) << RST_RESET_USB_PHY_SUSPEND_OVERRIDE_LSB) & RST_RESET_USB_PHY_SUSPEND_OVERRIDE_MASK)
// #define RST_RESET_USB_PHY_SUSPEND_OVERRIDE_RESET	1'd0
#define RST_RESET_LUT_RESET_MSB				2
#define RST_RESET_LUT_RESET_LSB				2
#define RST_RESET_LUT_RESET_MASK			0x00000004
#define RST_RESET_LUT_RESET_GET(x)			(((x) & RST_RESET_LUT_RESET_MASK) >> RST_RESET_LUT_RESET_LSB)
#define RST_RESET_LUT_RESET_SET(x)			(((x) << RST_RESET_LUT_RESET_LSB) & RST_RESET_LUT_RESET_MASK)
// #define RST_RESET_LUT_RESET_RESET			1'd0
#define RST_RESET_MBOX_RESET_MSB			1
#define RST_RESET_MBOX_RESET_LSB			1
#define RST_RESET_MBOX_RESET_MASK			0x00000002
#define RST_RESET_MBOX_RESET_GET(x)			(((x) & RST_RESET_MBOX_RESET_MASK) >> RST_RESET_MBOX_RESET_LSB)
#define RST_RESET_MBOX_RESET_SET(x)			(((x) << RST_RESET_MBOX_RESET_LSB) & RST_RESET_MBOX_RESET_MASK)
// #define RST_RESET_MBOX_RESET_RESET			1'd0
#define RST_RESET_I2S_RESET_MSB				0
#define RST_RESET_I2S_RESET_LSB				0
#define RST_RESET_I2S_RESET_MASK			0x00000001
#define RST_RESET_I2S_RESET_GET(x)			(((x) & RST_RESET_I2S_RESET_MASK) >> RST_RESET_I2S_RESET_LSB)
#define RST_RESET_I2S_RESET_SET(x)			(((x) << RST_RESET_I2S_RESET_LSB) & RST_RESET_I2S_RESET_MASK)
// #define RST_RESET_I2S_RESET_RESET			1'd0
#define RST_RESET_ADDRESS				0x1806001c
#define RST_RESET_OFFSET				0x001c
// SW modifiable bits
#define RST_RESET_SW_MASK				0xffffffff
// bits defined at reset
#define RST_RESET_RSTMASK				0xffffffff
// reset value (ignore bits undefined at reset)
#define RST_RESET_RESET				0x28c07ff0

#define ETH_CFG_SW_APB_ACCESS_MSB			9
#define ETH_CFG_SW_APB_ACCESS_LSB			9
#define ETH_CFG_SW_APB_ACCESS_MASK			0x00000200
#define ETH_CFG_SW_APB_ACCESS_GET(x)			(((x) & ETH_CFG_SW_APB_ACCESS_MASK) >> ETH_CFG_SW_APB_ACCESS_LSB)
#define ETH_CFG_SW_APB_ACCESS_SET(x)			(((x) << ETH_CFG_SW_APB_ACCESS_LSB) & ETH_CFG_SW_APB_ACCESS_MASK)
// #define ETH_CFG_SW_APB_ACCESS_RESET			1'd0
#define ETH_CFG_ADDRESS					0x18070000
#define ETH_CFG_OFFSET					0x0000
// SW modifiable bits
#define ETH_CFG_SW_MASK					0x00003fff
// bits defined at reset
#define ETH_CFG_RSTMASK					0xffffffff
// reset value (ignore bits undefined at reset)
#define ETH_CFG_RESET					0x00003000


// 32'h18040000 (GPIO_OE)
#define GPIO_OE_OE_MSB					31
#define GPIO_OE_OE_LSB					0
#define GPIO_OE_OE_MASK					0xffffffff
#define GPIO_OE_OE_GET(x)				(((x) & GPIO_OE_OE_MASK) >> GPIO_OE_OE_LSB)
#define GPIO_OE_OE_SET(x)				(((x) << GPIO_OE_OE_LSB) & GPIO_OE_OE_MASK)
//#define GPIO_OE_OE_RESET				32'd193291
#define GPIO_OE_ADDRESS					0x18040000
#define GPIO_OE_OFFSET					0x0000

// 32'h180b8024 (MDIO_PHY_ADDR)
#define MDIO_PHY_ADDR_VALUE_MSB				2
#define MDIO_PHY_ADDR_VALUE_LSB				0
#define MDIO_PHY_ADDR_VALUE_MASK			0x00000007
#define MDIO_PHY_ADDR_VALUE_GET(x)			(((x) & MDIO_PHY_ADDR_VALUE_MASK) >> MDIO_PHY_ADDR_VALUE_LSB)
#define MDIO_PHY_ADDR_VALUE_SET(x)			(((x) << MDIO_PHY_ADDR_VALUE_LSB) & MDIO_PHY_ADDR_VALUE_MASK)
//#define MDIO_PHY_ADDR_VALUE_RESET			3'd7
#define MDIO_PHY_ADDR_ADDRESS				0x180b8024
#define MDIO_PHY_ADDR_OFFSET				0x0024
// SW modifiable bits
#define MDIO_PHY_ADDR_SW_MASK				0x00000007
// bits defined at reset
#define MDIO_PHY_ADDR_RSTMASK				0xffffffff
// reset value (ignore bits undefined at reset)
#define MDIO_PHY_ADDR_RESET				0x00000007

#define GPIO_OUT_FUNCTION1_ADDRESS			0x18040030
#define GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_MSB		15
#define GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_LSB		8
#define GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_MASK		0x0000ff00
#define GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_GET(x)		(((x) & GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_MASK) >> GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_LSB)
#define GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_SET(x)		(((x) << GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_LSB) & GPIO_OUT_FUNCTION1_ENABLE_GPIO_5_MASK)

#define GPIO_OUT_FUNCTION4_ADDRESS			0x1804003c
#define GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_MSB           15
#define GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_LSB           8
#define GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_MASK          0x0000ff00
#define GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_GET(x)        (((x) & GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_MASK) >> GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_LSB)
#define GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_SET(x)        (((x) << GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_LSB) & GPIO_OUT_FUNCTION4_ENABLE_GPIO_17_MASK)

// 32'h18040050 (GPIO_IN_ENABLE3)
#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_MSB		31
#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_LSB		24
#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_MASK		0xff000000
#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_GET(x)		(((x) & GPIO_IN_ENABLE3_BOOT_EXT_MDC_MASK) >> GPIO_IN_ENABLE3_BOOT_EXT_MDC_LSB)
#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_SET(x)		(((x) << GPIO_IN_ENABLE3_BOOT_EXT_MDC_LSB) & GPIO_IN_ENABLE3_BOOT_EXT_MDC_MASK)
//#define GPIO_IN_ENABLE3_BOOT_EXT_MDC_RESET		8'd0
#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_MSB		23
#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_LSB		16
#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_MASK		0x00ff0000
#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_GET(x)		(((x) & GPIO_IN_ENABLE3_BOOT_EXT_MDO_MASK) >> GPIO_IN_ENABLE3_BOOT_EXT_MDO_LSB)
#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_SET(x)		(((x) << GPIO_IN_ENABLE3_BOOT_EXT_MDO_LSB) & GPIO_IN_ENABLE3_BOOT_EXT_MDO_MASK)
//#define GPIO_IN_ENABLE3_BOOT_EXT_MDO_RESET		8'd0
#define GPIO_IN_ENABLE3_EXT_MDC_MSB			15
#define GPIO_IN_ENABLE3_EXT_MDC_LSB			8
#define GPIO_IN_ENABLE3_EXT_MDC_MASK			0x0000ff00
#define GPIO_IN_ENABLE3_EXT_MDC_GET(x)			(((x) & GPIO_IN_ENABLE3_EXT_MDC_MASK) >> GPIO_IN_ENABLE3_EXT_MDC_LSB)
#define GPIO_IN_ENABLE3_EXT_MDC_SET(x)			(((x) << GPIO_IN_ENABLE3_EXT_MDC_LSB) & GPIO_IN_ENABLE3_EXT_MDC_MASK)
//#define GPIO_IN_ENABLE3_EXT_MDC_RESET			8'd12
#define GPIO_IN_ENABLE3_EXT_MDO_MSB			7
#define GPIO_IN_ENABLE3_EXT_MDO_LSB			0
#define GPIO_IN_ENABLE3_EXT_MDO_MASK			0x000000ff
#define GPIO_IN_ENABLE3_EXT_MDO_GET(x)			(((x) & GPIO_IN_ENABLE3_EXT_MDO_MASK) >> GPIO_IN_ENABLE3_EXT_MDO_LSB)
#define GPIO_IN_ENABLE3_EXT_MDO_SET(x)			(((x) << GPIO_IN_ENABLE3_EXT_MDO_LSB) & GPIO_IN_ENABLE3_EXT_MDO_MASK)
//#define GPIO_IN_ENABLE3_EXT_MDO_RESET			8'd11
#define GPIO_IN_ENABLE3_ADDRESS				0x18040050
#define GPIO_IN_ENABLE3_OFFSET				0x0050
// SW modifiable bits
#define GPIO_IN_ENABLE3_SW_MASK				0xffffffff
// bits defined at reset
#define GPIO_IN_ENABLE3_RSTMASK				0xffffffff
// reset value (ignore bits undefined at reset)
#define GPIO_IN_ENABLE3_RESET				0x00000c0b

#define RST_REVISION_ID_VALUE_MSB                                    31
#define RST_REVISION_ID_VALUE_LSB                                    0
#define RST_REVISION_ID_VALUE_MASK                                   0xffffffff
#define RST_REVISION_ID_VALUE_GET(x)                                 (((x) & RST_REVISION_ID_VALUE_MASK) >> RST_REVISION_ID_VALUE_LSB)
#define RST_REVISION_ID_VALUE_SET(x)                                 (((x) << RST_REVISION_ID_VALUE_LSB) & RST_REVISION_ID_VALUE_MASK)
//#define RST_REVISION_ID_VALUE_RESET                                  32'd4544
#define RST_REVISION_ID_ADDRESS                                      0x18060090
#define RST_REVISION_ID_OFFSET                                       0x0090

#define RST_BOOTSTRAP_SW_OPTION4_MSB                                 20
#define RST_BOOTSTRAP_SW_OPTION4_LSB                                 20
#define RST_BOOTSTRAP_SW_OPTION4_MASK                                0x00100000
#define RST_BOOTSTRAP_SW_OPTION4_GET(x)                              (((x) & RST_BOOTSTRAP_SW_OPTION4_MASK) >> RST_BOOTSTRAP_SW_OPTION4_LSB)
#define RST_BOOTSTRAP_SW_OPTION4_SET(x)                              (((x) << RST_BOOTSTRAP_SW_OPTION4_LSB) & RST_BOOTSTRAP_SW_OPTION4_MASK)
//#define RST_BOOTSTRAP_SW_OPTION4_RESET                               1'd0
#define RST_BOOTSTRAP_SW_OPTION3_MSB                                 19
#define RST_BOOTSTRAP_SW_OPTION3_LSB                                 19
#define RST_BOOTSTRAP_SW_OPTION3_MASK                                0x00080000
#define RST_BOOTSTRAP_SW_OPTION3_GET(x)                              (((x) & RST_BOOTSTRAP_SW_OPTION3_MASK) >> RST_BOOTSTRAP_SW_OPTION3_LSB)
#define RST_BOOTSTRAP_SW_OPTION3_SET(x)                              (((x) << RST_BOOTSTRAP_SW_OPTION3_LSB) & RST_BOOTSTRAP_SW_OPTION3_MASK)
//#define RST_BOOTSTRAP_SW_OPTION3_RESET                               1'd0
#define RST_BOOTSTRAP_SW_OPTION2_MSB                                 18
#define RST_BOOTSTRAP_SW_OPTION2_LSB                                 18
#define RST_BOOTSTRAP_SW_OPTION2_MASK                                0x00040000
#define RST_BOOTSTRAP_SW_OPTION2_GET(x)                              (((x) & RST_BOOTSTRAP_SW_OPTION2_MASK) >> RST_BOOTSTRAP_SW_OPTION2_LSB)
#define RST_BOOTSTRAP_SW_OPTION2_SET(x)                              (((x) << RST_BOOTSTRAP_SW_OPTION2_LSB) & RST_BOOTSTRAP_SW_OPTION2_MASK)
//#define RST_BOOTSTRAP_SW_OPTION2_RESET                               1'd0
#define RST_BOOTSTRAP_SW_OPTION1_MSB                                 17
#define RST_BOOTSTRAP_SW_OPTION1_LSB                                 17
#define RST_BOOTSTRAP_SW_OPTION1_MASK                                0x00020000
#define RST_BOOTSTRAP_SW_OPTION1_GET(x)                              (((x) & RST_BOOTSTRAP_SW_OPTION1_MASK) >> RST_BOOTSTRAP_SW_OPTION1_LSB)
#define RST_BOOTSTRAP_SW_OPTION1_SET(x)                              (((x) << RST_BOOTSTRAP_SW_OPTION1_LSB) & RST_BOOTSTRAP_SW_OPTION1_MASK)
//#define RST_BOOTSTRAP_SW_OPTION1_RESET                               1'd0
#define RST_BOOTSTRAP_TESTMODE_SELECT_MSB                            16
#define RST_BOOTSTRAP_TESTMODE_SELECT_LSB                            16
#define RST_BOOTSTRAP_TESTMODE_SELECT_MASK                           0x00010000
#define RST_BOOTSTRAP_TESTMODE_SELECT_GET(x)                         (((x) & RST_BOOTSTRAP_TESTMODE_SELECT_MASK) >> RST_BOOTSTRAP_TESTMODE_SELECT_LSB)
#define RST_BOOTSTRAP_TESTMODE_SELECT_SET(x)                         (((x) << RST_BOOTSTRAP_TESTMODE_SELECT_LSB) & RST_BOOTSTRAP_TESTMODE_SELECT_MASK)
//#define RST_BOOTSTRAP_TESTMODE_SELECT_RESET                          1'd0
#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_MSB                          15
#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_LSB                          15
#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_MASK                         0x00008000
#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_GET(x)                       (((x) & RST_BOOTSTRAP_BURNIN_TEST_MBIST_MASK) >> RST_BOOTSTRAP_BURNIN_TEST_MBIST_LSB)
#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_SET(x)                       (((x) << RST_BOOTSTRAP_BURNIN_TEST_MBIST_LSB) & RST_BOOTSTRAP_BURNIN_TEST_MBIST_MASK)
//#define RST_BOOTSTRAP_BURNIN_TEST_MBIST_RESET                        1'd0
#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_MSB                           14
#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_LSB                           14
#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_MASK                          0x00004000
#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_GET(x)                        (((x) & RST_BOOTSTRAP_BURNIN_TEST_ATPG_MASK) >> RST_BOOTSTRAP_BURNIN_TEST_ATPG_LSB)
#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_SET(x)                        (((x) << RST_BOOTSTRAP_BURNIN_TEST_ATPG_LSB) & RST_BOOTSTRAP_BURNIN_TEST_ATPG_MASK)
//#define RST_BOOTSTRAP_BURNIN_TEST_ATPG_RESET                         1'd0
#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_MSB                    12
#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_LSB                    12
#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_MASK                   0x00001000
#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_GET(x)                 (((x) & RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_MASK) >> RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_LSB)
#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_SET(x)                 (((x) << RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_LSB) & RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_MASK)
//#define RST_BOOTSTRAP_RADIO_USB_PLL_TEST_MODE_RESET                  1'd0
#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_MSB                       11
#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_LSB                       11
#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_MASK                      0x00000800
#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_GET(x)                    (((x) & RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_MASK) >> RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_LSB)
#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_SET(x)                    (((x) << RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_LSB) & RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_MASK)
//#define RST_BOOTSTRAP_RADIO_ONLY_TEST_MODE_RESET                     1'd0
#define RST_BOOTSTRAP_TESTROM_SELECT_MSB                             10
#define RST_BOOTSTRAP_TESTROM_SELECT_LSB                             10
#define RST_BOOTSTRAP_TESTROM_SELECT_MASK                            0x00000400
#define RST_BOOTSTRAP_TESTROM_SELECT_GET(x)                          (((x) & RST_BOOTSTRAP_TESTROM_SELECT_MASK) >> RST_BOOTSTRAP_TESTROM_SELECT_LSB)
#define RST_BOOTSTRAP_TESTROM_SELECT_SET(x)                          (((x) << RST_BOOTSTRAP_TESTROM_SELECT_LSB) & RST_BOOTSTRAP_TESTROM_SELECT_MASK)
//#define RST_BOOTSTRAP_TESTROM_SELECT_RESET                           1'd1
#define RST_BOOTSTRAP_OTP_POR_ENABLE_MSB                             9
#define RST_BOOTSTRAP_OTP_POR_ENABLE_LSB                             9
#define RST_BOOTSTRAP_OTP_POR_ENABLE_MASK                            0x00000200
#define RST_BOOTSTRAP_OTP_POR_ENABLE_GET(x)                          (((x) & RST_BOOTSTRAP_OTP_POR_ENABLE_MASK) >> RST_BOOTSTRAP_OTP_POR_ENABLE_LSB)
#define RST_BOOTSTRAP_OTP_POR_ENABLE_SET(x)                          (((x) << RST_BOOTSTRAP_OTP_POR_ENABLE_LSB) & RST_BOOTSTRAP_OTP_POR_ENABLE_MASK)
//#define RST_BOOTSTRAP_OTP_POR_ENABLE_RESET                           1'd1
#define RST_BOOTSTRAP_SRIF_ENABLE_MSB                                8
#define RST_BOOTSTRAP_SRIF_ENABLE_LSB                                8
#define RST_BOOTSTRAP_SRIF_ENABLE_MASK                               0x00000100
#define RST_BOOTSTRAP_SRIF_ENABLE_GET(x)                             (((x) & RST_BOOTSTRAP_SRIF_ENABLE_MASK) >> RST_BOOTSTRAP_SRIF_ENABLE_LSB)
#define RST_BOOTSTRAP_SRIF_ENABLE_SET(x)                             (((x) << RST_BOOTSTRAP_SRIF_ENABLE_LSB) & RST_BOOTSTRAP_SRIF_ENABLE_MASK)
//#define RST_BOOTSTRAP_SRIF_ENABLE_RESET                              1'd1
#define RST_BOOTSTRAP_USB_HOST_MODE_MSB                              7
#define RST_BOOTSTRAP_USB_HOST_MODE_LSB                              7
#define RST_BOOTSTRAP_USB_HOST_MODE_MASK                             0x00000080
#define RST_BOOTSTRAP_USB_HOST_MODE_GET(x)                           (((x) & RST_BOOTSTRAP_USB_HOST_MODE_MASK) >> RST_BOOTSTRAP_USB_HOST_MODE_LSB)
#define RST_BOOTSTRAP_USB_HOST_MODE_SET(x)                           (((x) << RST_BOOTSTRAP_USB_HOST_MODE_LSB) & RST_BOOTSTRAP_USB_HOST_MODE_MASK)
//#define RST_BOOTSTRAP_USB_HOST_MODE_RESET                            1'd1
#define RST_BOOTSTRAP_RC_SELECT_MSB                                  6
#define RST_BOOTSTRAP_RC_SELECT_LSB                                  6
#define RST_BOOTSTRAP_RC_SELECT_MASK                                 0x00000040
#define RST_BOOTSTRAP_RC_SELECT_GET(x)                               (((x) & RST_BOOTSTRAP_RC_SELECT_MASK) >> RST_BOOTSTRAP_RC_SELECT_LSB)
#define RST_BOOTSTRAP_RC_SELECT_SET(x)                               (((x) << RST_BOOTSTRAP_RC_SELECT_LSB) & RST_BOOTSTRAP_RC_SELECT_MASK)
//#define RST_BOOTSTRAP_RC_SELECT_RESET                                1'd1
#define RST_BOOTSTRAP_JTAG_MODE_MSB                                  5
#define RST_BOOTSTRAP_JTAG_MODE_LSB                                  5
#define RST_BOOTSTRAP_JTAG_MODE_MASK                                 0x00000020
#define RST_BOOTSTRAP_JTAG_MODE_GET(x)                               (((x) & RST_BOOTSTRAP_JTAG_MODE_MASK) >> RST_BOOTSTRAP_JTAG_MODE_LSB)
#define RST_BOOTSTRAP_JTAG_MODE_SET(x)                               (((x) << RST_BOOTSTRAP_JTAG_MODE_LSB) & RST_BOOTSTRAP_JTAG_MODE_MASK)
//#define RST_BOOTSTRAP_JTAG_MODE_RESET                                1'd1
#define RST_BOOTSTRAP_REF_CLK_25_MSB                                 4
#define RST_BOOTSTRAP_REF_CLK_25_LSB                                 4
#define RST_BOOTSTRAP_REF_CLK_25_MASK                                0x00000010
#define RST_BOOTSTRAP_REF_CLK_25_GET(x)                              (((x) & RST_BOOTSTRAP_REF_CLK_25_MASK) >> RST_BOOTSTRAP_REF_CLK_25_LSB)
#define RST_BOOTSTRAP_REF_CLK_25_SET(x)                              (((x) << RST_BOOTSTRAP_REF_CLK_25_LSB) & RST_BOOTSTRAP_REF_CLK_25_MASK)
//#define RST_BOOTSTRAP_REF_CLK_25_RESET                               1'd1
#define RST_BOOTSTRAP_DDR_WIDTH_16_MSB                               3
#define RST_BOOTSTRAP_DDR_WIDTH_16_LSB                               3
#define RST_BOOTSTRAP_DDR_WIDTH_16_MASK                              0x00000008
#define RST_BOOTSTRAP_DDR_WIDTH_16_GET(x)                            (((x) & RST_BOOTSTRAP_DDR_WIDTH_16_MASK) >> RST_BOOTSTRAP_DDR_WIDTH_16_LSB)
#define RST_BOOTSTRAP_DDR_WIDTH_16_SET(x)                            (((x) << RST_BOOTSTRAP_DDR_WIDTH_16_LSB) & RST_BOOTSTRAP_DDR_WIDTH_16_MASK)
//#define RST_BOOTSTRAP_DDR_WIDTH_16_RESET                             1'd1
#define RST_BOOTSTRAP_EXT_BOOT_SELECT_MSB                            2
#define RST_BOOTSTRAP_EXT_BOOT_SELECT_LSB                            2
#define RST_BOOTSTRAP_EXT_BOOT_SELECT_MASK                           0x00000004
#define RST_BOOTSTRAP_EXT_BOOT_SELECT_GET(x)                         (((x) & RST_BOOTSTRAP_EXT_BOOT_SELECT_MASK) >> RST_BOOTSTRAP_EXT_BOOT_SELECT_LSB)
#define RST_BOOTSTRAP_EXT_BOOT_SELECT_SET(x)                         (((x) << RST_BOOTSTRAP_EXT_BOOT_SELECT_LSB) & RST_BOOTSTRAP_EXT_BOOT_SELECT_MASK)
//#define RST_BOOTSTRAP_EXT_BOOT_SELECT_RESET                          1'd1
#define RST_BOOTSTRAP_SDRAM_SELECT_MSB                               1
#define RST_BOOTSTRAP_SDRAM_SELECT_LSB                               1
#define RST_BOOTSTRAP_SDRAM_SELECT_MASK                              0x00000002
#define RST_BOOTSTRAP_SDRAM_SELECT_GET(x)                            (((x) & RST_BOOTSTRAP_SDRAM_SELECT_MASK) >> RST_BOOTSTRAP_SDRAM_SELECT_LSB)
#define RST_BOOTSTRAP_SDRAM_SELECT_SET(x)                            (((x) << RST_BOOTSTRAP_SDRAM_SELECT_LSB) & RST_BOOTSTRAP_SDRAM_SELECT_MASK)
//#define RST_BOOTSTRAP_SDRAM_SELECT_RESET                             1'd1
#define RST_BOOTSTRAP_DDR_SELECT_MSB                                 0
#define RST_BOOTSTRAP_DDR_SELECT_LSB                                 0
#define RST_BOOTSTRAP_DDR_SELECT_MASK                                0x00000001
#define RST_BOOTSTRAP_DDR_SELECT_GET(x)                              (((x) & RST_BOOTSTRAP_DDR_SELECT_MASK) >> RST_BOOTSTRAP_DDR_SELECT_LSB)
#define RST_BOOTSTRAP_DDR_SELECT_SET(x)                              (((x) << RST_BOOTSTRAP_DDR_SELECT_LSB) & RST_BOOTSTRAP_DDR_SELECT_MASK)
//#define RST_BOOTSTRAP_DDR_SELECT_RESET                               1'd0
#define RST_BOOTSTRAP_ADDRESS                                        0x180600b0
#define RST_BOOTSTRAP_OFFSET                                         0x00b0


#define PCIE_PLL_CONFIG_UPDATING_MSB                                 31
#define PCIE_PLL_CONFIG_UPDATING_LSB                                 31
#define PCIE_PLL_CONFIG_UPDATING_MASK                                0x80000000
#define PCIE_PLL_CONFIG_UPDATING_GET(x)                              (((x) & PCIE_PLL_CONFIG_UPDATING_MASK) >> PCIE_PLL_CONFIG_UPDATING_LSB)
#define PCIE_PLL_CONFIG_UPDATING_SET(x)                              (((x) << PCIE_PLL_CONFIG_UPDATING_LSB) & PCIE_PLL_CONFIG_UPDATING_MASK)
//#define PCIE_PLL_CONFIG_UPDATING_RESET                               1'd0
#define PCIE_PLL_CONFIG_PLLPWD_MSB                                   30
#define PCIE_PLL_CONFIG_PLLPWD_LSB                                   30
#define PCIE_PLL_CONFIG_PLLPWD_MASK                                  0x40000000
#define PCIE_PLL_CONFIG_PLLPWD_GET(x)                                (((x) & PCIE_PLL_CONFIG_PLLPWD_MASK) >> PCIE_PLL_CONFIG_PLLPWD_LSB)
#define PCIE_PLL_CONFIG_PLLPWD_SET(x)                                (((x) << PCIE_PLL_CONFIG_PLLPWD_LSB) & PCIE_PLL_CONFIG_PLLPWD_MASK)
//#define PCIE_PLL_CONFIG_PLLPWD_RESET                                 1'd1
#define PCIE_PLL_CONFIG_BYPASS_MSB                                   16
#define PCIE_PLL_CONFIG_BYPASS_LSB                                   16
#define PCIE_PLL_CONFIG_BYPASS_MASK                                  0x00010000
#define PCIE_PLL_CONFIG_BYPASS_GET(x)                                (((x) & PCIE_PLL_CONFIG_BYPASS_MASK) >> PCIE_PLL_CONFIG_BYPASS_LSB)
#define PCIE_PLL_CONFIG_BYPASS_SET(x)                                (((x) << PCIE_PLL_CONFIG_BYPASS_LSB) & PCIE_PLL_CONFIG_BYPASS_MASK)
//#define PCIE_PLL_CONFIG_BYPASS_RESET                                 1'd1
#define PCIE_PLL_CONFIG_REFDIV_MSB                                   14
#define PCIE_PLL_CONFIG_REFDIV_LSB                                   10
#define PCIE_PLL_CONFIG_REFDIV_MASK                                  0x00007c00
#define PCIE_PLL_CONFIG_REFDIV_GET(x)                                (((x) & PCIE_PLL_CONFIG_REFDIV_MASK) >> PCIE_PLL_CONFIG_REFDIV_LSB)
#define PCIE_PLL_CONFIG_REFDIV_SET(x)                                (((x) << PCIE_PLL_CONFIG_REFDIV_LSB) & PCIE_PLL_CONFIG_REFDIV_MASK)
//#define PCIE_PLL_CONFIG_REFDIV_RESET                                 5'd1
#define PCIE_PLL_CONFIG_ADDRESS                                      0x18050010
#define PCIE_PLL_CONFIG_OFFSET                                       0x0010
#endif	/* _APB_MAP_H */
