obj-$(CONFIG_ATHEROS_RATE_SAMPLE)	+= ath_rate/sample/
obj-$(CONFIG_ATHEROS_RATE_ONOE)		+= ath_rate/onoe/
obj-$(CONFIG_ATHEROS_RATE_AMRR)		+= ath_rate/amrr/
obj-$(CONFIG_ATHEROS)			+= ath/ ath_hal/ net80211/
