#
# Makefile for plugins on Solaris 2
#
# $Id: //depot/sw/releases/Aquila_9.2.0_U11/apps/pppoe/ppp-2.4.4/pppd/plugins/Makefile.sol2#1 $
#

include ../../Makedefs.com

CFLAGS	= -c -O -I.. -I../../include $(COPTS)
LDFLAGS	= -G 

all:	minconn.so

minconn.so: minconn.o
	ld -o $@ $(LDFLAGS) -h $@ minconn.o

minconn.o: minconn.c
	$(CC) $(CFLAGS) -c $? 

passprompt.so: passprompt.o
	ld -o $@ $(LDFLAGS) -h $@ passprompt.o

passprompt.o: passprompt.c
	$(CC) $(CFLAGS) -c $?

clean:
	rm -f *.o *.so
