#!/bin/sh

IP_MAC_FILE=/configure_backup/ip_mac.conf
UDHCPD_FILE=/etc/udhcpd.conf

if [ ! -f /etc/ip_mac.conf ]; then
	touch /configure_backup/ip_mac.conf
fi

cat $IP_MAC_FILE | grep "enable" | awk 'BEGIN{OFS=FS=" "}{print $1,$2,$3}' >> $UDHCPD_FILE


