# Makefile for busybox
#
# Copyright (C) 1999-2004 by Erik Andersen <andersen@codepoet.org>
#
# Licensed under the GPL v2 or later, see the file LICENSE in this tarball.
#

#ifndef HAVE_IF_INDEX
#COMPAT_SOURCES=  \
#	libbridge_compat.c
#else
#COMPAT_SOURCES=
#endif

LIBBRIDGE_SOURCES= \
	$(COMPAT_SOURCES) \
	libbridge_devif.c \
	libbridge_if.c \
	libbridge_init.c \
	libbridge_misc.c

lib-$(CONFIG_BRCTL):=$(LIBBRIDGE_SOURCES:.c=.o)
