#!/bin/sh
echo "[luodp] go caldata"
if [ ! -f /etc/cal.bin ]; then
	echo "Backup caldata at `date`"  >> /etc/callog.txt 
	dd if=/dev/caldata of=/etc/cal.bin
fi
CAL_MSG=`dmesg | grep 'Using Cal data from Driver Default Settings'`
if [ -n "$CAL_MSG" ]; then
	echo "Restore caldata at `date`"  >> /etc/callog.txt    
	dd if=/etc/cal.bin of=/dev/caldata
	/etc/ath/apdown
	/etc/ath/apup
fi

#added by yhl 2013.12.20 below
echo "mac backup"
if [ ! -f /etc/mac.bin ]; then
	echo "Backup mac at `date`"  >> /etc/maclog.txt
	ifconfig | grep eth0 | awk -F ' ' '{print$5}' > /etc/mac.bin
	cfg -a ETH0_DFMAC=`cat /etc/mac.bin`
	cfg -a ETH0_MAC=`cat /etc/mac.bin`
	cfg -a BR0_MAC=`ifconfig | grep br0 | awk -F ' ' '{print$5}'`
	cfg -c
fi
#added by yhl 2013.12.20 above
