#!/bin/sh

if [ ! -f /configure_backup/nvram.bin ]; then
	echo "[luodp] Backup nvram"
	echo "Backup nvram at `date`"  >> /etc/callog.txt 
	dd if=/dev/nvram of=/configure_backup/nvram.bin
fi
CAL_MSG=`cfg -e |grep FACTORY`
if [ -z "$CAL_MSG" ]; then
	echo "[luodp] Restore nvram"
	echo "Restore nvram at `date`"  >> /etc/callog.txt    
    rm /tmp/.apcfg
	dd if=/configure_backup/nvram.bin of=/dev/nvram
    cfg -a FACTORY=0
    cfg -c
#	/etc/ath/apdown
#	/etc/ath/apup
fi

#check /dev/caldata
if [ ! -f /configure_backup/cal.bin ]; then
	echo "[luodp] Backup caldata"
	echo "Backup caldata at `date`"  >> /etc/callog.txt 
    echo FACTORY | dd of=/dev/caldata bs=1 count=7 seek=32768
	dd if=/dev/caldata of=/configure_backup/cal.bin
fi
CAL_MSG=`dd if=/dev/caldata bs=1 count=7 skip=32768`
if [ "$CAL_MSG" != "FACTORY" ];then
	echo "[luodp] Restore caldata"
	echo "Restore caldata at `date`"  >> /etc/callog.txt    
	dd if=/configure_backup/cal.bin of=/dev/caldata

    echo FACTORY | dd of=/dev/caldata bs=1 count=7 seek=32768
fi

#added by yhl 2013.12.20 below

if [ -f /etc/mac.bin ]; then
	ETH0_DFMAC=`cfg -e |grep ETH0_DFMAC`
	if [ -z "$ETH0_DFMAC" ]; then
		cfg -a ETH0_DFMAC=`cat /etc/mac.bin`
	fi
	ETH0_MAC=`cfg -e |grep ETH0_MAC`
	if [ -z "$ETH0_MAC" ]; then
		cfg -a ETH0_MAC=`cat /etc/mac.bin`
	fi
	BR0_MAC=`cfg -e |grep BR0_MAC`
	if [ -z "$BR0_MAC" ]; then
		cfg -a BR0_MAC=`ifconfig | grep br0 | awk -F ' ' '{print $5}'`
	fi
	cfg -c
fi
#added by yhl 2013.12.20 above

#add by mingyue for terminal backup
#MSG=`cfg -e | grep "TERMINAL_BKP" | awk -F "=" '{print $2}'`
#if [ "${MSG}" = "1" ]; then
#    if [ -d /configure_backup/terminal_dev_register ]; then
#        rm -r /var/terminal_dev_register > /dev/null 2>&1
#        cp -r /configure_backup/terminal_dev_register  /var/ > /dev/null 2>&1
#    fi
#    cfg -a TERMINAL_BKP=0
#    cfg -c
#fi
