#!/bin/sh
if [ $# -ne 2 ] ;then
       echo "Usage: repeatVAP on on"
        exit 1
fi
ath_num=`ifconfig  | grep -c ath`
number_pci=`grep -c 168c /proc/bus/pci/devices`
if [ $number_pci = 1 ]; then
	if [ "$ath_num" = "5" ];then
		/etc/ath/killVAP ath4
	else if [ "$ath_num" = "6" ];then
		/etc/ath/killVAP ath4	
		/etc/ath/killVAP ath5
	fi
	fi
else if [ $number_pci = 0 ]; then
	if [ "$ath_num" = "3" ];then
		/etc/ath/killVAP ath2
	fi
fi
fi

wifi_flag=`cfg -e | grep  WIFION_OFF= | awk -F'=' '{print $2}'`
wifi_flag_2=`cfg -e | grep  WIFION_OFF_3= | awk -F'=' '{print $2}'`
wds2g_flag=`echo $1 | grep on`
wds5g_flag=`echo $2 | grep on`
if [ "${wifi_flag}" = "on" -a ! -z "${wds2g_flag}" ];then
ifconfig ath0 down;ifconfig ath0 up
ifconfig ath1 down;ifconfig ath1 up
fi

if [ "${wifi_flag_2}" = "on" -a ! -z "${wds5g_flag}" ];then
ifconfig ath2 down;ifconfig ath2 up
ifconfig ath3 down;ifconfig ath3 up
fi

. /etc/ath/apcfg_simple

APMODE="ap-wds-ind"
STAMODE="sta-wds-ind"

#work_flag=`cfg -e | grep  AP_STARTMODE= | awk -F'=' '{print $2}'`
#work_flag2=`cfg -e | grep  AP_STARTMODE= | awk -F'"' '{print $2}'`
if [ "${AP_STARTMODE}" = "repeater_wisp" ];then
#	echo repeater_wisp--------------------
	ifconfig eth0 down
else
	if [ "${WAN_MODE}" != "bridged" ]; then
		if [ "${WAN_MODE}" = "dhcp" ]; then
			##
			## Run the DHCP client on this interface
			##

			udhcpc -b -i eth0 -h HBD-Router -s /etc/udhcpc.script
		elif [ "${WAN_MODE}" = "static" ]; then
			##
			## Static IP address
			##

			ifconfig eth0 $WAN_IPADDR netmask $WAN_NETMASK up
			if [ "${IPGW}" != "" ]
			then
				route add default gw ${IPGW}
			fi

		elif [ "${WAN_MODE}" = "pppoe" ]; then
			##
			## pppoe
			##

			pppoe-start
			cfg -a PRIDNS=`awk -F' ' 'BEGIN{i=0;}{i++; if(i==1) {print $2}}' /etc/resolv.conf`
			cfg -a SECDNS=`awk -F' ' 'BEGIN{i=0;}{i++; if(i==2) {print $2}}' /etc/resolv.conf`
			cfg -c
		fi
	fi
fi

if [ $number_pci = 1 ]; then
	VAP_NUM=3
else
	VAP_NUM=1
fi

wds_flag=`cfg -e | grep  WISPON_OFF= | awk -F'=' '{print $2}'`

if [ "${wds_flag}" = "on" ];then
	if [ "s$WISP_STA_SSID" != "s" ];then
		makeVAP ${STAMODE} "$WISP_STA_SSID" $WISP_STA_RADIO_ID:$WISP_STA_RFPARAM
	    	if [ $? != 0 ]; then
	        	echo "Unable to create VAP!"
        		exit
		fi
		VAP_NUM=$(($VAP_NUM+1))
		if [ "${WISP_STA_SECMODE}" != "WPA" -a "${WISP_ROOTAP_MAC}" != "" ]; then
        		iwconfig ath$VAP_NUM ap $WISP_ROOTAP_MAC
		fi
	fi
fi
	
if [ $number_pci = 1 ]; then
	wds_flag_2=`cfg -e | grep  WISPON_OFF_3= | awk -F'=' '{print $2}'`
	if [ "${wds_flag_2}" = "on" ];then
		if [ "s$WISP_STA_SSID_2" != "s" ];then
			makeVAP ${STAMODE} "$WISP_STA_SSID_2" $WISP_STA_RADIO_ID_2:$WISP_STA_RFPARAM_3
			if [ $? != 0 ]; then
				echo "Unable to create VAP!"
				exit
			fi
			VAP_NUM=$(($VAP_NUM+1))
			if [ "${WISP_STA_SECMODE_2}" != "WPA" -a "${WISP_ROOTAP_MAC_2}" != "" ]; then
				iwconfig ath$VAP_NUM ap $WISP_ROOTAP_MAC_2
			fi
		fi
	fi
fi

if [ $number_pci = 1 ]; then
	VAP_NUM=4
else
	VAP_NUM=2
fi

if [ "${wds_flag}" = "on" ];then
	if [ "s$WISP_STA_SSID" != "s" ];then
	#	echo "------------there are task"
		pid_2g_sta=`ps | grep "udhcpc -b -i ath${VAP_NUM}" | awk -F' ' '{print $1}'`
	#	echo ---------------- $pid_2g_sta

		
		if [ ! -z "${pid_2g_sta}" ]; then
	#		echo "------------there are task"
			kill -9 $pid_2g_sta
		fi
	    activateVAP ath$VAP_NUM:$WISP_STA_RADIO_ID - $WISP_STA_SECMODE $WISP_STA_SECFILE $WISP_WPS_ENABLE
		if [ -f /tmp/sta_conf_filename ];then
		    wpa_supplicant `cat /tmp/sta_conf_filename` &
			sleep 2
		fi
		nat_wwan.sh ath$VAP_NUM
		VAP_NUM_2=$VAP_NUM
		VAP_NUM=$(($VAP_NUM+1))
	fi
fi

if [ $number_pci = 1 ]; then
	if [ "${wds_flag_2}" = "on" ];then	
		if [ "s$WISP_STA_SSID_2" != "s" ];then
			pid_5g_sta=`ps | grep "udhcpc -b -i ath${VAP_NUM}" | awk -F' ' '{print $1}'"`
			if [ ! -z "${pid_5g_sta}" ];then
				kill -9 $pid_5g_sta
			fi
			rm -fr /tmp/sta_conf_filename
			activateVAP ath$VAP_NUM:$WISP_STA_RADIO_ID_2 - $WISP_STA_SECMODE_2 $WISP_STA_SECFILE_2 $WISP_WPS_ENABLE_2
			if [ -f /tmp/sta_conf_filename ]; then
				wpa_supplicant `cat /tmp/sta_conf_filename` &				
			fi
			nat_wwan.sh ath$VAP_NUM
		fi
	fi
fi

if [ "${wds_flag}" = "on" ];then
	if [ "s$WISP_STA_SSID" != "s" ];then
		sleep 30
		wisp_flag=`cfg -e | grep WISP_MODE_2G | awk -F'=' '{print $2}'`
                if [ "${wisp_flag}" = "dhcp" ];then
                        udhcpc -b -i ath$VAP_NUM_2 -h HBD-Router -s /etc/udhcpc.script
                elif [ "${wisp_flag}" = "static" ]; then
                        ifconfig ath$VAP_NUM_2 $WISP_IPADDR_2G netmask $WISP_NETMASK_2G up
                        if [ "${WISP_GW_2G}" != "" ]
                        then
                                route add default gw ${WISP_GW_2G}
                        fi
                fi
#		udhcpc -b -i ath$VAP_NUM_2 -h HBD-Router -s /etc/udhcpc.script
	fi
fi

if [ $number_pci = 1 ]; then
	if [ "${wds_flag_2}" = "on" ];then	
		if [ "s$WISP_STA_SSID_2" != "s" ];then
			if [ "${wds_flag}" = "on" ];then
				sleep 3
			else
				sleep 30
			fi
	                wisp_flag=`cfg -e | grep WISP_MODE_5G | awk -F'=' '{print $2}'`
	                if [ "${wisp_flag}" = "dhcp" ];then
	                        udhcpc -b -i ath$VAP_NUM -h HBD-Router -s /etc/udhcpc.script
	                elif [ "${wisp_flag}" = "static" ]; then
	                        ifconfig ath$VAP_NUM $WISP_IPADDR_5G netmask $WISP_NETMASK_5G up
	                        if [ "${WISP_GW_5G}" != "" ]
	                        then
	                                route add default gw ${WISP_GW_5G}
	                        fi
	                fi
#				udhcpc -b -i ath$VAP_NUM -h HBD-Router -s /etc/udhcpc.script
		fi
	fi
fi
