#!/bin/sh
if [ $# -ne 2 ] ;then
       echo "Usage: repeatVAP on on"
        exit 1
fi
ath_num=`ifconfig  | grep -c ath`
number_pci=`grep -c 168c /proc/bus/pci/devices`
if [ $number_pci = 1 ]; then
	if [ "$ath_num" = "5" ];then
		/etc/ath/killVAP ath4
	else if [ "$ath_num" = "6" ];then
		/etc/ath/killVAP ath4	
		/etc/ath/killVAP ath5
	fi
	fi
else if [ $number_pci = 0 ]; then
	if [ "$ath_num" = "3" ];then
		/etc/ath/killVAP ath2
	fi
fi
fi

wifi_flag=`cfg -e | grep  WIFION_OFF= | awk -F'=' '{print $2}'`
wifi_flag_2=`cfg -e | grep  WIFION_OFF_3= | awk -F'=' '{print $2}'`
wds2g_flag=`echo $1 | grep on`
wds5g_flag=`echo $2 | grep on`
if [ "${wifi_flag}" = "on" -a ! -z "${wds2g_flag}" ];then
ifconfig ath0 down;ifconfig ath0 up
ifconfig ath1 down;ifconfig ath1 up
fi

if [ "${wifi_flag_2}" = "on" -a ! -z "${wds5g_flag}" ];then
ifconfig ath2 down;ifconfig ath2 up
ifconfig ath3 down;ifconfig ath3 up
fi

. /etc/ath/apcfg

APMODE="ap-wds"
STAMODE="sta-wds"

#work_flag=`cfg -e | grep  AP_STARTMODE= | awk -F'=' '{print $2}'`
#if [ "${work_flag}" = "repeater" ];then
#	ifconfig eth0 down
#fi

if [ $number_pci = 1 ]; then
	VAP_NUM=3
else
	VAP_NUM=1
fi

wds_flag=`cfg -e | grep  WDSON_OFF= | awk -F'=' '{print $2}'`

if [ "${wds_flag}" = "on" ];then
	if [ "s$STA_SSID" != "s" ];then
		makeVAP ${STAMODE} "$STA_SSID" $STA_RADIO_ID:$STA_RFPARAM
	    	if [ $? != 0 ]; then
	        	echo "Unable to create VAP!"
        		exit
		fi
		VAP_NUM=$(($VAP_NUM+1))
		if [ "${STA_SECMODE}" != "WPA" -a "${ROOTAP_MAC}" != "" ]; then
        		iwconfig ath$VAP_NUM ap $ROOTAP_MAC
		fi
	fi
fi
	
if [ $number_pci = 1 ]; then
	wds_flag_2=`cfg -e | grep  WDSON_OFF_3= | awk -F'=' '{print $2}'`
	if [ "${wds_flag_2}" = "on" ];then
		if [ "s$STA_SSID_2" != "s" ];then
			makeVAP ${STAMODE} "$STA_SSID_2" $STA_RADIO_ID_2:$STA_RFPARAM_3
			if [ $? != 0 ]; then
				echo "Unable to create VAP!"
				exit
			fi
			VAP_NUM=$(($VAP_NUM+1))
			if [ "${STA_SECMODE_2}" != "WPA" -a "${ROOTAP_MAC_2}" != "" ]; then
				iwconfig ath$VAP_NUM ap $ROOTAP_MAC_2
			fi
		fi
	fi
fi

if [ $number_pci = 1 ]; then
	VAP_NUM=4
else
	VAP_NUM=2
fi

if [ "${wds_flag}" = "on" ];then
	if [ "s$STA_SSID" != "s" ];then
	#	echo "------------there are task"
		pid_2g_sta=`ps | grep "udhcpc -b -i ath${VAP_NUM}" | awk -F' ' '{print $1}'`
	#	echo ---------------- $pid_2g_sta

		
		if [ ! -z "${pid_2g_sta}" ]; then
	#		echo "------------there are task"
			kill -9 $pid_2g_sta
		fi
	    activateVAP ath$VAP_NUM:$STA_RADIO_ID - $STA_SECMODE $STA_SECFILE $WPS_ENABLE
		if [ -f /tmp/sta_conf_filename ];then
		    wpa_supplicant `cat /tmp/sta_conf_filename` &
			sleep 2
		fi
		nat_wwan.sh ath$VAP_NUM
		sleep 5
		udhcpc -b -i ath$VAP_NUM -h HBD-Router -s /etc/udhcpc.script
		VAP_NUM=$(($VAP_NUM+1))
	fi
fi

if [ $number_pci = 1 ]; then
	if [ "${wds_flag_2}" = "on" ];then	
		if [ "s$STA_SSID_2" != "s" ];then
			pid_5g_sta=`ps | grep "udhcpc -b -i ath${VAP_NUM}" | awk -F' ' '{print $1}'"`
			#echo ---------------- $pid_5g_sta
			if [ ! -z "${pid_5g_sta}" ];then
			#	echo "--------------there are task"
				kill -9 $pid_5g_sta
			fi
			rm -fr /tmp/sta_conf_filename
			activateVAP ath$VAP_NUM:$STA_RADIO_ID_2 - $STA_SECMODE_2 $STA_SECFILE_2 $WPS_ENABLE_2
			if [ -f /tmp/sta_conf_filename ]; then
				wpa_supplicant `cat /tmp/sta_conf_filename` &				
			fi
			nat_wwan.sh ath$VAP_NUM
			sleep 5
			udhcpc -b -i ath$VAP_NUM -h HBD-Router -s /etc/udhcpc.script
		fi
	fi
fi
