#!/bin/sh
if [ $# -ne 2 ] ;then
       echo "Usage: repeatVAP on on"
        exit 1
fi
ath_num=`ifconfig  | grep -c ath`
number_pci=`grep -c 168c /proc/bus/pci/devices`
if [ $number_pci = 1 ]; then
	if [ "$ath_num" = "5" ];then
		/etc/ath/killVAP ath4
	else if [ "$ath_num" = "6" ];then
		/etc/ath/killVAP ath4	
		/etc/ath/killVAP ath5
	fi
	fi
else if [ $number_pci = 0 ]; then
	if [ "$ath_num" = "3" ];then
		/etc/ath/killVAP ath2
	fi
fi
fi

wifi_flag=`cfg -e | grep  WIFION_OFF= | awk -F'=' '{print $2}'`
wifi_flag_2=`cfg -e | grep  WIFION_OFF_3= | awk -F'=' '{print $2}'`
wds2g_flag=`echo $1 | grep on`
wds5g_flag=`echo $2 | grep on`
if [ "${wifi_flag}" = "on" -a ! -z "${wds2g_flag}" ];then
ifconfig ath0 down;ifconfig ath0 up
ifconfig ath1 down;ifconfig ath1 up
fi

if [ "${wifi_flag_2}" = "on" -a ! -z "${wds5g_flag}" ];then
ifconfig ath2 down;ifconfig ath2 up
ifconfig ath3 down;ifconfig ath3 up
fi

. /etc/ath/apcfg_simple


APMODE="ap-wds"
STAMODE="sta-wds"

if [ $number_pci = 1 ]; then
	VAP_NUM=3
else
	VAP_NUM=1
fi

wds_flag=`cfg -e | grep  WDSON_OFF= | awk -F'=' '{print $2}'`

if [ "${wds_flag}" = "on" ];then
	if [ "s$WDS_STA_SSID" != "s" ];then
		makeVAP ${STAMODE} "$WDS_STA_SSID" $WDS_STA_RADIO_ID:$WDS_STA_RFPARAM
	    	if [ $? != 0 ]; then
	        	echo "Unable to create VAP!"
        		exit
		fi
		VAP_NUM=$(($VAP_NUM+1))
		if [ "${WDS_STA_SECMODE}" != "WPA" -a "${WDS_ROOTAP_MAC}" != "" ]; then
        		iwconfig ath$VAP_NUM ap $WDS_ROOTAP_MAC
		fi
	fi
fi
	
if [ $number_pci = 1 ]; then
	wds_flag_2=`cfg -e | grep  WDSON_OFF_3= | awk -F'=' '{print $2}'`
	if [ "${wds_flag_2}" = "on" ];then
		if [ "s$WDS_STA_SSID_2" != "s" ];then
			makeVAP ${STAMODE} "$WDS_STA_SSID_2" $WDS_STA_RADIO_ID_2:$WDS_STA_RFPARAM_3
			if [ $? != 0 ]; then
				echo "Unable to create VAP!"
				exit
			fi
			VAP_NUM=$(($VAP_NUM+1))
			if [ "${WDS_STA_SECMODE_2}" != "WPA" -a "${WDS_ROOTAP_MAC_2}" != "" ]; then
				iwconfig ath$VAP_NUM ap $WDS_ROOTAP_MAC_2
			fi
		fi
	fi
fi

if [ $number_pci = 1 ]; then
	VAP_NUM=4
else
	VAP_NUM=2
fi

if [ "${wds_flag}" = "on" ];then
	if [ "s$WDS_STA_SSID" != "s" ];then
	    activateVAP ath$VAP_NUM:$WDS_STA_RADIO_ID br0 $WDS_STA_SECMODE $WDS_STA_SECFILE $WDS_WPS_ENABLE
		VAP_NUM=$(($VAP_NUM+1))
		if [ -f /tmp/sta_conf_filename ]; then
		    wpa_supplicant `cat /tmp/sta_conf_filename` &
			sleep 2
		fi
	fi
fi

if [ $number_pci = 1 ]; then
	if [ "${wds_flag_2}" = "on" ];then	
		if [ "s$WDS_STA_SSID_2" != "s" ];then
			rm -fr /tmp/sta_conf_filename
			activateVAP ath$VAP_NUM:$WDS_STA_RADIO_ID_2 br0 $WDS_STA_SECMODE_2 $WDS_STA_SECFILE_2 $WDS_WPS_ENABLE_2
			if [ -f /tmp/sta_conf_filename ]; then
				wpa_supplicant `cat /tmp/sta_conf_filename` &
			fi
		fi
	fi
fi
