#!/bin/sh

BACKUP_DIR="/configure_backup/backup/"
BACKUP_LIST="/configure_backup/backup/backup_list.conf"


if [ x$1 = x ]; then
	exit 1
fi

BACKUP_DATE=`cfg -e | grep "$1" |awk -F'=' '{print $2}' | awk -F'"' '{print $2}'`
if [ -z $BACKUP_DATE ];then
	exit 1
fi

str=$(grep -i -E "\<$1\>" $BACKUP_LIST)

if [ "$str" = "" ];then
        echo "the backup is not exist"
		exit 1
else
        echo "the backup is exist"
		sed -i '/'$1'/d' $BACKUP_LIST
		rm $BACKUP_DIR/$BACKUP_DATE.bin
		rm $BACKUP_DIR/$BACKUP_DATE.sta*
		rm $BACKUP_DIR/$BACKUP_DATE.ip_mac.conf
		rm $BACKUP_DIR/$BACKUP_DATE.route.conf
		rm $BACKUP_DIR/$BACKUP_DATE.arp_ip_mac.conf
		rm $BACKUP_DIR/$BACKUP_DATE.arp_ip_mac_on.conf
		rm $BACKUP_DIR/$BACKUP_DATE.portmap
		rm $BACKUP_DIR/$BACKUP_DATE.parc
		rm $BACKUP_DIR/$BACKUP_DATE.pwd.xml
        echo "delete backup done"
        exit 1
fi
