#!/bin/sh

BACKUP_DIR="/configure_backup/backup/"
BACKUP_LIST="/configure_backup/backup/backup_list.conf"


if [ ! -d "$BACKUP_DIR" ]; then 
	mkdir "$BACKUP_DIR" 
fi 
if [ ! -f "$BACKUP_LIST" ]; then
	touch "$BACKUP_LIST"
fi

if [ x$1 = x ]; then
	exit 1
fi

BACKUP_DATE=`cfg -e | grep "$1" |awk -F'=' '{print $2}' | awk -F'"' '{print $2}'`
if [ -z $BACKUP_DATE ];then
	exit 1
fi

str=$(grep -i "\<$1\>" $BACKUP_LIST)

if [ "$str" = "" ];then
        echo "the backup is not exist"
		echo  "$1 $BACKUP_DATE" >> $BACKUP_LIST
		dd if=/dev/nvram of=$BACKUP_DIR/$BACKUP_DATE.bin
		cp /configure_backup/.staAcl $BACKUP_DIR/$BACKUP_DATE.staAcl
		cp /configure_backup/.staMac $BACKUP_DIR/$BACKUP_DATE.staMac
		cp /configure_backup/ip_mac.conf $BACKUP_DIR/$BACKUP_DATE.ip_mac.conf
		cp /configure_backup/route.conf $BACKUP_DIR/$BACKUP_DATE.route.conf
		cp /configure_backup/arp_ip_mac.conf $BACKUP_DIR/$BACKUP_DATE.arp_ip_mac.conf
		cp /configure_backup/ath/iptables/portmap $BACKUP_DIR/$BACKUP_DATE.portmap
		cp /configure_backup/ath/iptables/parc $BACKUP_DIR/$BACKUP_DATE.parc
else
        echo "the backup is exist"
        exit 1
fi

echo "backup done"
