#!/bin/sh

BACKUP_LIST="/configure_backup/backup/backup_list.conf"
#mac factory
#backup
#if [ -f /etc/mac.bin ]; then
##	cfg -a ETH0_DFMAC=`cat /etc/mac.bin`
#	cfg -a ETH0_MAC=`cat /etc/mac.bin`
#	cfg -a BR0_MAC=`ifconfig | grep br0 | awk -F ' ' '{print$5}'`
#fi

if [ -f "$BACKUP_LIST" ]; then

	cat $BACKUP_LIST | while read line
	do
		name=`echo $line | awk '{print $1}'`
		value=`echo $line | awk '{print $2}'`
		cfg -a $name="$value"
	done
	
fi
cfg -c
echo "var back done"
