#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
mount -o remount +w /

#
# Mount the RAM filesystem to /tmp
#

mount -t ramfs -n none /tmp

export PATH=$PATH:/etc/ath

insmod /lib/modules/2.6.31/net/athrs_gmac.ko
insmod /lib/modules/2.6.31/i2s/ar7240_i2s.ko

##
## Export the current system configuration
##

. /etc/ath/apcfg

##
## Bring up the network
##

ifconfig $WAN_IF up
ifconfig $LAN_IF up
/etc/rc.d/rc.network
/etc/rc.d/rc.bridge

#
# Enable USB
#
hci=o	# for python
grep virian /proc/cmdline > /dev/null 2>&1
[ $? -eq 0 ] && hci=e	# for virian

insmod /lib/modules/2.6.31/usb/usbcore.ko
insmod /lib/modules/2.6.31/usb/${hci}hci-hcd.ko
insmod /lib/modules/2.6.31/usb/usb-storage.ko

#
# Untar the debug tools into /tmp/tools
#

mkdir /tmp/tools
cd /tmp/tools
tar -xzvf /sbin/debug.tgz
export PATH=$PATH:/tmp/tools

/usr/sbin/telnetd
/usr/sbin/httpd -h /usr/www/
/bin/factoryreset /dev/freset

# start the page cache/kmem cache cleanup timer in the kernel
echo 1 > /proc/sys/vm/drop_caches

##
## Determine if auto start of AP is required
##

if [ "${WLAN_ON_BOOT}" = "y" ]; then
    /etc/ath/apup
fi


