
extern void ip6t_ah_init(void);
extern void ip6t_dst_init(void);
extern void ip6t_eui64_init(void);
extern void ip6t_frag_init(void);
extern void ip6t_hbh_init(void);
extern void ip6t_hl_init(void);
extern void ip6t_HL_init(void);
extern void ip6t_icmp6_init(void);
extern void ip6t_ipv6header_init(void);
extern void ip6t_LOG_init(void);
extern void ip6t_mh_init(void);
extern void ip6t_REJECT_init(void);
extern void ip6t_rt_init(void);
extern void xt_CLASSIFY_init(void);
extern void xt_cluster_init(void);
extern void xt_comment_init(void);
extern void xt_connbytes_init(void);
extern void xt_connlimit_init(void);
extern void xt_connmark_init(void);
extern void xt_CONNMARK_init(void);
extern void xt_CONNSECMARK_init(void);
extern void xt_conntrack_init(void);
extern void xt_dccp_init(void);
extern void xt_dscp_init(void);
extern void xt_DSCP_init(void);
extern void xt_esp_init(void);
extern void xt_hashlimit_init(void);
extern void xt_helper_init(void);
extern void xt_iprange_init(void);
extern void xt_length_init(void);
extern void xt_limit_init(void);
extern void xt_mac_init(void);
extern void xt_mark_init(void);
extern void xt_MARK_init(void);
extern void xt_multiport_init(void);
extern void xt_NFLOG_init(void);
extern void xt_NFQUEUE_init(void);
extern void xt_NOTRACK_init(void);
extern void xt_owner_init(void);
extern void xt_physdev_init(void);
extern void xt_pkttype_init(void);
extern void xt_policy_init(void);
extern void xt_quota_init(void);
extern void xt_rateest_init(void);
extern void xt_recent_init(void);
extern void xt_sctp_init(void);
extern void xt_SECMARK_init(void);
extern void xt_socket_init(void);
extern void xt_standard_init(void);
extern void xt_state_init(void);
extern void xt_statistic_init(void);
extern void xt_string_init(void);
extern void xt_tcp_init(void);
extern void xt_tcpmss_init(void);
extern void xt_TCPMSS_init(void);
extern void xt_TCPOPTSTRIP_init(void);
extern void xt_time_init(void);
extern void xt_tos_init(void);
extern void xt_TOS_init(void);
extern void xt_TPROXY_init(void);
extern void xt_TRACE_init(void);
extern void xt_u32_init(void);
extern void xt_udp_init(void);
extern void xt_IMQ_init(void);
extern void xt_webstr_init(void);
void init_extensions(void) {
	ip6t_ah_init();
	ip6t_dst_init();
	ip6t_eui64_init();
	ip6t_frag_init();
	ip6t_hbh_init();
	ip6t_hl_init();
	ip6t_HL_init();
	ip6t_icmp6_init();
	ip6t_ipv6header_init();
	ip6t_LOG_init();
	ip6t_mh_init();
	ip6t_REJECT_init();
	ip6t_rt_init();
	xt_CLASSIFY_init();
	xt_cluster_init();
	xt_comment_init();
	xt_connbytes_init();
	xt_connlimit_init();
	xt_connmark_init();
	xt_CONNMARK_init();
	xt_CONNSECMARK_init();
	xt_conntrack_init();
	xt_dccp_init();
	xt_dscp_init();
	xt_DSCP_init();
	xt_esp_init();
	xt_hashlimit_init();
	xt_helper_init();
	xt_iprange_init();
	xt_length_init();
	xt_limit_init();
	xt_mac_init();
	xt_mark_init();
	xt_MARK_init();
	xt_multiport_init();
	xt_NFLOG_init();
	xt_NFQUEUE_init();
	xt_NOTRACK_init();
	xt_owner_init();
	xt_physdev_init();
	xt_pkttype_init();
	xt_policy_init();
	xt_quota_init();
	xt_rateest_init();
	xt_recent_init();
	xt_sctp_init();
	xt_SECMARK_init();
	xt_socket_init();
	xt_standard_init();
	xt_state_init();
	xt_statistic_init();
	xt_string_init();
	xt_tcp_init();
	xt_tcpmss_init();
	xt_TCPMSS_init();
	xt_TCPOPTSTRIP_init();
	xt_time_init();
	xt_tos_init();
	xt_TOS_init();
	xt_TPROXY_init();
	xt_TRACE_init();
	xt_u32_init();
	xt_udp_init();
	xt_IMQ_init();
	xt_webstr_init();
}
