#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
mount -o remount +w /

#added by yhl 2013.11.13
mknod /dev/ppp c 108 0
mkdir -p /var/local/tmp/ppp/status

#
# Mount the RAM filesystem to /tmp
#

mount -t ramfs -n none /tmp

export PATH=$PATH:/etc/ath
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib
cd /lib;
ln -s libsqlite3.so.0.8.6 libsqlite3.so.0
cd /root


# for profile-based-optimization
grep -iq "debugfs" /proc/filesystems
if [ $? -eq 0 ]
then
	grep -iq "sysfs" /proc/filesystems
	if [ $? -eq 0 ]
	then
		if [ ! -d /sys ]
		then
			mkdir /sys >/dev/null 2>&1
		fi

		mount -t sysfs none /sys >/dev/null 2>&1
		if [ $? -eq 0 ]
		then
			mount -t debugfs none /sys/kernel/debug >/dev/null 2>&1
			if [ $? -eq 0 ]
			then
				echo "** sysfs & debugfs mounted successfully **"
			else
				echo "****** debugfs mount failure ******"
			fi
					
		else
			echo "****** sysfs mount failure ******"
		fi
	fi
fi

insmod /lib/modules/2.6.31/net/athrs_gmac.ko

##
## Put the names of the interfaces in the environmental variables
## (They can be board unique)
##

export WAN_IF=eth0
export LAN_IF=eth1

ifconfig $WAN_IF up
ifconfig $LAN_IF up
/etc/rc.d/rc.network
/etc/rc.d/rc.bridge
. /etc/ath/apcfg

#
# Enable USB
#
insmod /lib/modules/2.6.31/usb/usbcore.ko
insmod /lib/modules/2.6.31/usb/ehci-hcd.ko
insmod /lib/modules/2.6.31/usb/usb-storage.ko
insmod /lib/modules/2.6.31/usb/usbnet.ko
insmod /lib/modules/2.6.31/usb/cdc_ether.ko

#
# Enable I2S
#
#insmod /lib/modules/2.6.31/i2s/ath_i2s.ko

#
# Untar the debug tools into /tmp/tools
#

mkdir /tmp/tools
cd /tmp/tools
tar -xzvf /sbin/debug.tgz

/usr/sbin/telnetd
/usr/sbin/httpd -h /usr/www/ -c /etc/httpd.conf
/bin/factoryreset /dev/freset

# start the page cache/kmem cache cleanup timer in the kernel
echo 1 > /proc/sys/vm/drop_caches

# when processes uses page-cache more than 30% of system memory,
# lets force them to write
echo 20 > /proc/sys/vm/dirty_ratio

# when the dirty pages cross more than 5% of sys memory,
# kick in the pdflush
echo 5 > /proc/sys/vm/dirty_background_ratio

##
## Check for Auto AP Start
##

if [ "${WLAN_ON_BOOT}" = "y" ]; then
    /etc/ath/apup
fi

##
## nat settings 
##
/etc/rc.d/rc.modules
/etc/nat_vlan.sh
if [ "${PRIDNS}" != "" ]
then
	echo "nameserver ${PRIDNS}" > /etc/resolv.conf
else
	echo "nameserver 8.8.8.8" > /etc/resolv.conf
fi
if [ "${SECDNS}" != "" ]
then
	echo "nameserver ${SECDNS}" >> /etc/resolv.conf
fi
##
## dhcp
##
/etc/rc.d/rc.udhcpd
/usr/sbin/udhcpd /etc/udhcpd.conf
##
## add si3000 and spi node
##
if [ -c /dev/spiS0 ]
then
	echo "/dev/spiS0 node exist"
else
	mknod /dev/spiS0 c 217 0
fi
if [ -c /dev/pcm0 ]
then
	echo "/dev/pcm0 node exist"
else
	mknod /dev/pcm0 c 252 0
fi
insmod /lib/modules/2.6.31/si3000/ath_si3000.ko
insmod /lib/modules/2.6.31/stm32/ath_spi_stm32.ko

mkdir -p /var/terminal_init/log


spi_rt_main & 
terminal_dev_register &
swipe_card &
monitor_application  &

/bin/reset_mips /bin/phone_serv_19200 &
/bin/server &
net_test &
/usr/bin/cal_check
/usr/bin/version_check