#
# pppdump Makefile for SVR4 systems
# $Id: //depot/sw/releases/Aquila_9.2.0_U11/apps/pppoe/ppp-2.4.4/pppdump/Makefile.sol2#1 $
#

include ../Makedefs.com

CFLAGS= $(COPTS) -I../include/net
OBJS = pppdump.o bsd-comp.o deflate.o zlib.o

all:	pppdump

pppdump: $(OBJS)
	$(CC) -o pppdump $(OBJS)

clean:
	rm -f $(OBJS) pppdump *~

install:
	$(INSTALL) -f $(BINDIR) pppdump
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppdump.8
