#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
mount -o remount +w /

#
# Mount the RAM filesystem to /tmp
#

mount -t ramfs -n none /tmp

export PATH=$PATH:/etc/ath

insmod /lib/modules/2.6.15/net/ag7240_mod.ko

##
## Get the default settings from apcfg
##

. /etc/ath/apcfg

##
## Bring up the network
##

ifconfig $WAN_IF up
ifconfig $LAN_IF up
/etc/rc.d/rc.network
/etc/rc.d/rc.bridge

#
# Enable USB
#
hci=o	# for python
grep virian /proc/cmdline > /dev/null 2>&1
[ $? -eq 0 ] && hci=e	# for virian

insmod /lib/modules/2.6.15/usb/usbcore.ko
insmod /lib/modules/2.6.15/usb/${hci}hci-hcd.ko
insmod /lib/modules/2.6.15/usb/usb-storage.ko

#
# Untar the debug tools into /tmp/tools
#

mkdir /tmp/tools
cd /tmp/tools
tar -xzvf /sbin/debug.tgz
export PATH=$PATH:/tmp/tools

/usr/sbin/telnetd
/usr/sbin/httpd -h /usr/www/
/bin/factoryreset /dev/freset

# start the page cache/kmem cache cleanup timer in the kernel
echo 1 > /proc/sys/vm/drop-cache

# when processes uses page-cache more than 30% of system memory, 
# lets force them to write
echo 20 > /proc/sys/vm/dirty_ratio
  
# when the dirty pages cross more than 5% of sys memory, 
# kick in the pdflush
echo 5 > /proc/sys/vm/dirty_background_ratio

##
## Check for Auto AP Start
##

if [ "${WLAN_ON_BOOT}" = "y" ]; then
    /etc/ath/apup
fi
