.Dd March 27, 1999
.Dt RIPQUERY 8
.Os "Linux NetKit (0.17)"
.Sh NAME
.Nm ripquery
.Nd send a RIP request to a remote host
.Sh SYNOPSIS
.Nm ripquery
.Op Fl n
host
.Sh DESCRIPTION
The
.Nm ripquery
command can be used to send a RIP request to a remote host.
If the remote host runs a RIP server it will reply to the
RIP request and sends its current routing table entries.
.Nm ripquery
will then print these entries. The option
.Fl n
can be used to suppress the IP number to name conversion.
.Sh SEE ALSO
.Xr routed 8

