#!/bin/sh
sed -e '/^ /d' -e 's/^/0x/' | awk --non-decimal-data 'BEGIN{lastaddr=0; lasttype="x"; lastname="xxx"} {if(lastaddr!=0) print ($1-lastaddr)" "lastaddr" "lasttype" "lastname; lastaddr=$1; lasttype=$2; lastname=$3} END{print "0 "lastaddr" "lasttype" "lastname}'

